This notebook generates n simulated replicates of the shendure dataset. As though the whole experiment were run n more times.

Imports

In [1]:
import scMPRAforge as scm
from dask.distributed import Client, LocalCluster

2025-10-06 17:46:44.936646: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-10-06 17:46:44.940944: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /vast/palmer/apps/avx2/software/Code-Server/4.17.0/lib:/vast/palmer/apps/avx2/software/gettext/0.22.5-GCCcore-13.3.0/lib:/vast/palmer/apps/avx2/software/libiconv/1.17-GCCcore-13.3.0/lib:/vast/palmer/apps/avx2/software/ncurses/6.5-GCCcore-13.3.0/lib:/vast/palmer/apps/avx2/software/libxml2/2.12.7-GCCcore-13.3.0/lib:/vast/palmer/apps/avx2/software/XZ/5.4.5-GCCcore-13.3.0/lib:/vast/palmer/apps/avx2/software/expat/2.6.2-GCCcore-13.3.0/lib:/vast/palmer/apps/avx2/software/cURL/8.7.1-GCCcore-13.3.0/lib:/vast/palmer/apps/avx2/software/OpenSSL/3/lib:/vast/palmer/apps/avx2/software/zlib/1.3.1-GCCcore-13.3.0/lib:/vast/palmer/apps/avx2/software/GCCcore/13.3.0/lib64
2025-10-06 17:46:44.940960: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

Set up cluster

In [2]:
cluster=LocalCluster(memory_limit='8GB')
client=Client(cluster)

Load shendure ortho

In [3]:
path="/gpfs/gibbs/pi/reilly/tabula_data/shendure"
name="ortho_primordial_v3"
data_root="/gpfs/gibbs/pi/reilly/tabula_data"
primordial=scm.ortho.load(client,path,name)

In [7]:
description=scm.describe_parameters(primordial.by_cell_type_parameters,
                        dat=primordial.training_data.data,
                        split="cell_type")
description

,cell_type,cre_id,rep_id,mu,zi,theta,cells,r,sigmasquare,p
0,SurfaceEctoderm,Bend5_chr4_8168,2B1,0.019027,0.024496,0.397735,52,0.397735,0.019937,0.954346
1,SurfaceEctoderm,Bend5_chr4_8168,2B2,0.019027,0.017732,0.397735,89,0.397735,0.019937,0.954346
2,SurfaceEctoderm,Bend5_chr4_8168,A1,0.019027,0.053106,0.397735,28,0.397735,0.019937,0.954346
3,SurfaceEctoderm,Bend5_chr4_8168,A2,0.019027,0.044080,0.397735,39,0.397735,0.019937,0.954346
4,SurfaceEctoderm,Bend5_chr4_8168,B1,0.019027,0.027387,0.397735,81,0.397735,0.019937,0.954346
...,...,...,...,...,...,...,...,...,...,...
8750,NeuroectodermRostral,ubcP,2B2,10.436092,0.002679,0.403506,292,0.403506,280.350592,0.037225
8751,NeuroectodermRostral,ubcP,A1,10.436092,0.014129,0.403506,80,0.403506,280.350592,0.037225
8752,NeuroectodermRostral,ubcP,A2,10.436092,0.003825,0.403506,85,0.403506,280.350592,0.037225
8753,NeuroectodermRostral,ubcP,B1,10.436092,0.004788,0.403506,88,0.403506,280.350592,0.037225
8754,NeuroectodermRostral,ubcP,B2,10.436092,0.005728,0.403506,85,0.403506,280.350592,0.037225

Create a ground-truth dataframe from the description.

In [14]:
gt=description[["cell_type","cre_id","mu"]].groupby(["cell_type","cre_id"]).agg(true_mean=("mu","mean")).reset_index()
gt

           cell_type              cre_id   true_mean
0     Cardiomyocytes     Bend5_chr4_8174    0.064510
1     Cardiomyocytes     Bend5_chr4_8175    1.636992
2     Cardiomyocytes     Bend5_chr4_8179    0.053898
3     Cardiomyocytes     Btg1_chr10_9578    3.505954
4     Cardiomyocytes  Cdk5r1_chr11_12559    0.283988
...              ...                 ...         ...
1457       reference   Txndc12_chr4_7978    3.854626
1458       reference              eef1aP  272.651740
1459       reference               pgk1P   60.703993
1460       reference           reference    0.165915
1461       reference                ubcP   38.765467

[1462 rows x 3 columns]

Abstract what the library looked like from the ortho training data. We will make the simplifying assumption that all MPRA bc are equal abundance in the original.

Create object

In [ ]:
batch_plus=scm.de_novo_simulation(
                        simulation_replicates=3,
                        experiment_bounds=scm.SHENDURE_BOUNDS,
                        ground_truth=,
                        library=)

Simulate & save

load, make orthos and save

Spot-check parameter recapitulation