In [1]:
import sys
import os
package_path = os.path.abspath("..")  
sys.path.insert(0, package_path)
#The path will be managed by conda or whatever on release, but this is fine for now.

import scMPRAforge as scm

#load the autoreload extension
%load_ext autoreload
#reload code on every execution
#(this may break objects)
#you can remove this & do dev in a notebook, then paste into the module when you are done.
%autoreload 2

scm.helloworld()

hello world!

# flattening barcodes

In [1]:
import pandas as pd

In [6]:
dummy=pd.DataFrame({"bc":["AATC","AATC","ATGC","ATGC","AATG","TTGC"],"other_info":["foo","bar","baz","biff","bom","bim"]})
dummy

     bc other_info
0  AATC        foo
1  AATC        bar
2  ATGC        baz
3  ATGC       biff
4  AATG        bom
5  TTGC        bim

row 4 is a seq error of row 0/1, row 5 is a seq error of row 2/3.

In [7]:
scm.flatten_barcode_errors(dummy,barcode_column="bc")

     bc other_info
0  AATC        foo
1  AATC        bar
2  ATGC        baz
3  ATGC       biff
4  AATC        bom
5  ATGC        bim

perfect

# conversions

In [2]:
data_root="/gpfs/gibbs/pi/reilly/tabula_data"
scm.load_scMPRA_data(f"{data_root}/shendure/shendure_counts_grouped.txt")

,cell_bc,rep_id,cre_class,cre_id,cell_type,transfection_bc,mpra_bc,reads_transfection_bc,umis_transfection_bc,reads_mpra_bc,umis_mpra_bc,gex_umi,normalized_umis_mpra_bc
0,2B1_AAACCCACAAGGTTGG-1,2B1,devCRE,Btg1_chr10_9572,NeuroectodermBrain,CATCGCTGAGTAAACG,GCGTACTCACCAGGT,73,67,0,0,2376,0.000000
1,2B1_AAACCCACAAGGTTGG-1,2B1,devCRE,Gata4_chr14_5710,NeuroectodermBrain,GAGGATGAGTTGGAAT,CAATCGCACCCCCGA,167,159,0,0,2376,0.000000
2,2B1_AAACCCACAAGGTTGG-1,2B1,devCRE,Klf4_chr4_3952,NeuroectodermBrain,CGTGAATTAATTCTAT,AACCCGGTAAATGTA,99,89,0,0,2376,0.000000
3,2B1_AAACCCACAAGGTTGG-1,2B1,devCRE,Lama1_chr17_7793,NeuroectodermBrain,AGTAAGTCAGCTCTTT,CGTGACCTCTTCATT,159,147,0,0,2376,0.000000
4,2B1_AAACCCACAAGGTTGG-1,2B1,devCRE,Sox17_chr1_67,NeuroectodermBrain,GACAATAAAATTCCAT,ACAGTCACAAATTTA,59,58,0,0,2376,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
778243,B2_TTTGTTGGTGGACCAA-1,B2,devCRE,Sparc_chr11_7207,ExEndodermVisceral,AATAATCACTCAAATT,TACCAACTGAGACAT,130,104,0,0,1438,0.000000
778244,B2_TTTGTTGGTGGACCAA-1,B2,devCRE,Tgfbi_chr13_5735,ExEndodermVisceral,AGTCCATGGAGGGAGG,GTTTACCACATTACT,108,98,0,0,1438,0.000000
778245,B2_TTTGTTGGTGGACCAA-1,B2,devCRE,Tgfbi_chr13_5741,ExEndodermVisceral,CTCAAGTTAGTAAGGG,CAGGGAACTGCCACC,75,68,19,1,1438,2.082943
778246,B2_TTTGTTGGTGGACCAA-1,B2,promoters,noP,ExEndodermVisceral,"ACTTCTCGCCAAGGAA, GTTTCTTCGTCTGCCC","TCCCGCTGACACTTA, ATGTGGGTCGTCTAT",200,166,0,0,2876,0.000000
778247,B2_TTTGTTGGTGGACCAA-1,B2,promoters,pgk1P,ExEndodermVisceral,CGATCAATGACCATTC,TGGATAGCACAAATA,88,77,8,1,1438,2.082943