In [1]:
import pandas as pd
import numpy as np

In [19]:
summary=pd.read_csv("shendure_simulated_replicates_summary.tsv",sep="\t",index_col=0).drop(["simu_batch_replicate"],axis=1)
summary

,by,mean_squared_error,mean_biased_error,mean_absolute_percent_error,gt_type
0,cell_type,5.649055,-0.236400,34.906718,by_cre
1,cre_id,1.204023,0.072019,38.166087,by_cre
0,cell_type,5.645848,-0.235058,34.901852,by_cre
1,cre_id,1.201132,0.073599,38.166544,by_cre
0,cell_type,5.664349,-0.236472,34.888713,by_cre
...,...,...,...,...,...
1,cre_id,1.536217,0.170919,67.773052,by_cell_type
0,cell_type,2.252821,0.119780,22.048403,by_cell_type
1,cre_id,1.530610,0.167499,67.701865,by_cell_type
0,cell_type,2.252821,0.119780,22.048403,by_cell_type
1,cre_id,1.530610,0.167499,67.701865,by_cell_type

In [17]:
summary.groupby(["gt_type","by"]).agg("mean")[::-1]

                        mean_squared_error  mean_biased_error  \
gt_type      by
by_cre       cre_id               2.210055           0.106414
             cell_type            5.057432          -0.207487
by_cell_type cre_id               1.423266           0.165461
             cell_type            2.228713           0.116000

                        mean_absolute_percent_error
gt_type      by
by_cre       cre_id                       38.348821
             cell_type                    35.563264
by_cell_type cre_id                       68.096594
             cell_type                    22.046923

In [16]:
summary[summary["gt_type"]=="by_cell_type"].groupby(["gt_type","by"]).agg("mean")[::-1]

                        mean_squared_error  mean_biased_error  \
gt_type      by
by_cell_type cre_id               1.423266           0.165461
             cell_type            2.228713           0.116000

                        mean_absolute_percent_error
gt_type      by
by_cell_type cre_id                       68.096594
             cell_type                    22.046923