This notebook loads and performs minimal processing of relevant MPRA plasmid data from the seelig preprint.

In [4]:
import urllib.request
import pandas as pd
output_root="/gpfs/gibbs/pi/reilly/tabula_data/cohen"

We want R1 library data : 

> Combinatorial indexing scMPRA library preparation

> For HepG2, 2.5 million cells were electroporated with 11.5ug R1 ibrary plasmid DNA in [...]

> For K562, 2.5 million cells were electroporated with 11.5ug R1 library plasmid DNA in

In [3]:
urllib.request.urlretrieve("https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE269036&format=file&file=GSE269036%5FR1%2DMPRA%5Fprocessed%5Fdata%2Ecsv%2Egz",
    "/tmp/GSE269036_R1-MPRA_processed_data.csv.gz")

('/tmp/GSE269036_R1-MPRA_processed_data.csv.gz',
 <http.client.HTTPMessage at 0x145a8da1cda0>)

In [20]:
dna_counts=pd.read_csv("/tmp/GSE269036_R1-MPRA_processed_data.csv.gz")

In [14]:
dna_counts

,enhancer_sequence,barcodes,R1-MPRA_DNA,R1-MPRA_HepG2_replicate1,R1-MPRA_HepG2_replicate2,R1-MPRA_K562_replicate1,R1-MPRA_K562_replicate2
0,AAAACAAATGACTCACAACAACGATAACTCGCAAGAAAGCGCAGTC...,['AAAGACCGCC' 'AACAGTAGTC' 'AACTTGTGAG' 'AATAT...,4240,246,315,1033,1167
1,AAAATATCTCTGTAGGCAGATGCTTACAGCTGCTGCCGCAGACATA...,['AAACACGTTG' 'AAAGCCACAT' 'AACCACCTTG' 'AACTG...,1607,385,393,307,333
2,AAAATTAAACACTCGGGACTTGTCCGGGCATGCTGGCTGACTTGGC...,['AAATAGGCGA' 'AACACACAAC' 'AACTAATCCG' 'AACGG...,27327,45488,51307,1197,959
3,AAAATTAGCCGGGCGTGGTAGCAGGCGCCTGTAGTCCCAGCTACTC...,['AAACAGCGGG' 'AAAGCTAGTC' 'AACCATTACG' 'AACTG...,7337,252,307,960,1030
4,AAACAGGTCGGGGGTTAATCCATACACACGCTGGGGTTTTGCCCAG...,['AAATACGCCA' 'AACAAGCGTT' 'AACCGGCACA' 'AACGT...,12885,1162,1277,475,532
...,...,...,...,...,...,...,...
1341,TTTTTCTTACGCGGGTCATCACTCGTATGAAATGACTCACGCGACT...,['AAATCCAGGA' 'AACACCAGAT' 'AACTACTGGA' 'AACGG...,10030,859,897,1891,1779
1342,TTTTTGTTGGCGCGCGCGCCTGAAGCGGGACTGCCAGGTGGCGCGC...,['AAACTCGTAG' 'AAAGGACTGA' 'AACCTATCGT' 'AACGC...,3445,97,115,137,87
1343,TTTTTGTTTGACCCCTGTAATGTTTGTTCCCAGGGAACATGCCGGG...,['AAATTGGCTC' 'AACATCAGGT' 'AACTCCTCGG' 'AATAA...,4064,9196,10415,351,264
1344,TTTTTGTTTGTACAAAGCTCTGTTTGACCCCTGCGGGCATGCCGGG...,['AAATGAAGCC' 'AACATCCTGC' 'AACTCCGATT' 'AATAA...,4104,757,932,478,461
1345,TTTTTTGTTTTGTTCAATGTTGAACATTCTACCGGGATCATTGTTT...,['AAATTCAGGG' 'AACACGGACC' 'AACTCATGAG' 'AACGG...,12451,1495,1610,574,419

In [21]:
dna_counts=dna_counts[["enhancer_sequence","R1-MPRA_DNA"]].copy()
dna_counts.rename({"enhancer_sequence":"cre_id","R1-MPRA_DNA":"reads_DNA"},axis=1,inplace=True)

In [22]:
dna_counts

                                                 cre_id  reads_DNA
0     AAAACAAATGACTCACAACAACGATAACTCGCAAGAAAGCGCAGTC...       4240
1     AAAATATCTCTGTAGGCAGATGCTTACAGCTGCTGCCGCAGACATA...       1607
2     AAAATTAAACACTCGGGACTTGTCCGGGCATGCTGGCTGACTTGGC...      27327
3     AAAATTAGCCGGGCGTGGTAGCAGGCGCCTGTAGTCCCAGCTACTC...       7337
4     AAACAGGTCGGGGGTTAATCCATACACACGCTGGGGTTTTGCCCAG...      12885
...                                                 ...        ...
1341  TTTTTCTTACGCGGGTCATCACTCGTATGAAATGACTCACGCGACT...      10030
1342  TTTTTGTTGGCGCGCGCGCCTGAAGCGGGACTGCCAGGTGGCGCGC...       3445
1343  TTTTTGTTTGACCCCTGTAATGTTTGTTCCCAGGGAACATGCCGGG...       4064
1344  TTTTTGTTTGTACAAAGCTCTGTTTGACCCCTGCGGGCATGCCGGG...       4104
1345  TTTTTTGTTTTGTTCAATGTTGAACATTCTACCGGGATCATTGTTT...      12451

[1346 rows x 2 columns]

In [ ]:
dna_counts.to_csv("dna.tsv",sep="\t")