In [1]:
import scMPRAforge as scm
from dask.distributed import Client, LocalCluster

2026-01-16 15:15:20.252828: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-01-16 15:15:20.257292: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /apps/software/2024a/software/code-server/4.103.0/lib:/apps/software/2024a/software/gettext/0.22.5-GCCcore-13.3.0/lib:/apps/software/2024a/software/libiconv/1.17-GCCcore-13.3.0/lib:/apps/software/2024a/software/ncurses/6.5-GCCcore-13.3.0/lib:/apps/software/2024a/software/libxml2/2.12.7-GCCcore-13.3.0/lib:/apps/software/2024a/software/XZ/5.4.5-GCCcore-13.3.0/lib:/apps/software/2024a/software/expat/2.6.2-GCCcore-13.3.0/lib:/apps/software/2024a/software/cURL/8.7.1-GCCcore-13.3.0/lib:/apps/software/2024a/software/OpenSSL/3/lib64:/apps/software/2024a/software/zlib/1.3.1-GCCcore-13.3.0/lib:/apps/software/2024a/software/GCCcore/13.3.0/lib64
2026-01-16 15:15:20.257327: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

In [2]:
cluster=LocalCluster(memory_limit='24GB')
client = Client(cluster)

In [3]:
data_root="/nfs/roberts/project/pi_skr2/shared/tabula_data"
path=f"{data_root}/shendure"
name="ortho_primordial_v4"

In [4]:
primordial=scm.ortho.load(client,path,name)
shendure=primordial.training_data

In [5]:
shendure.data

,cell_bc,rep_id,transfection_bc,mpra_bc,cre_class,cre_id,reads_transfection_bc,umis_transfection_bc,reads_mpra_bc,umis_mpra_bc,cell_type,gex_umi,normalized_umis_mpra_bc,cre_id_original
0,A1_GTTACCCAGTTGAAGT-1,A1,GAAAGTGTATTTGGGT,ACGTAACATTATAAT,devCRE,Txndc12_chr4_7978,499,415,0,0,SurfaceEctoderm,3913,0.000000,Txndc12_chr4_7978
1,A1_GTTACCCAGTTGAAGT-1,A1,ACTGACGTCAATCAAT,TGTTTAAGTCAACAA,devCRE,Klf4_chr4_3952,850,678,0,0,SurfaceEctoderm,3913,0.000000,Klf4_chr4_3952
2,A1_GTTACCCAGTTGAAGT-1,A1,GGAGGTGTGCGCGTGG,CAACAACACATTTTA,devCRE,Foxa2_chr2_13840,549,451,0,0,SurfaceEctoderm,3913,0.000000,Foxa2_chr2_13840
3,A1_GTTACCCAGTTGAAGT-1,A1,CGATACCTACTTAATA,TACCTAATGGGAAAG,promoters,reference,413,353,0,0,SurfaceEctoderm,3913,0.000000,minP
4,A1_GTTACCCAGTTGAAGT-1,A1,CCGGGGTTGTAGGTAA,AAATGGTAAAAGGCA,devCRE,Lamc1_chr1_12152,319,258,0,0,SurfaceEctoderm,3913,0.000000,Lamc1_chr1_12152
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
781455,2B2_TTCTGTAAGGCTCTCG-1,2B2,CGACATTGGGGGATGC,CCCACAAAGGCACCA,devCRE,Txndc12_chr4_7961,14,14,0,0,NeuroectodermRostral,522,0.000000,Txndc12_chr4_7961
781456,2B2_TTCTGTAAGGCTCTCG-1,2B2,ATTTAGACACCAATAC,CAGCCCGCCGCCGAG,promoters,ubcP,32,31,196,11,NeuroectodermRostral,522,63.118754,ubcP
781457,2B2_TGGAACTCAATCCTAG-1,2B2,GTTAGATACGCTATGG,ATGGCACATATCTTA,devCRE,Gata4_chr14_5760,21,18,0,0,Mesoderm,968,0.000000,Gata4_chr14_5760
781458,2B2_TGGAACTCAATCCTAG-1,2B2,GATTAATTCGGTCTAC,CTCTATCGTCCTCGT,devCRE,Lamb1_chr12_2289,13,13,0,0,Mesoderm,968,0.000000,Lamb1_chr12_2289
781459,2B2_TGGAACTCAATCCTAG-1,2B2,AGACCATGCTGCGCGC,ATCGATTTATAATAC,promoters,pgk1P,15,14,30,3,Mesoderm,968,9.282867,pgk1P

https://scanpy.readthedocs.io/en/stable/tutorials/basics/clustering.html

> You may have noticed that the p-values found here are extremely low. This is due to the statistical test being performed considering each cell as an independent sample. For a more conservative approach you may want to consider “pseudo-bulking” your data by sample (e.g. sc.get.aggregate(adata, by=["sample", "cell_type"], func="sum", layer="counts")) and using a more powerful differential expression tool, like pydeseq2.

Seurat does something similar

https://satijalab.org/seurat/articles/de_vignette

I worry that variable number of cells, barcodes per cell, could mess this up. Ideally we would norm or subsample. But there is no info in the cohen paper suggesting that that's what they did, so I will go with the "default" suggested by the 2x popular libraries.

In [6]:
shendure.pseudobulk(subset="Mesoderm",split="cre_id")

       rep_id              cre_id  umis_mpra_bc
272        A1    Col5a1_chr2_2565             0
273        A1           reference             0
274        A1  Cdk5r1_chr11_12562             0
275        A1     Bend5_chr4_8174             0
276        A1    Gata4_chr14_5742             3
...       ...                 ...           ...
781419    2B2  Igfbp4_chr11_16710             0
781450    2B2    Lamc1_chr1_12189             0
781457    2B2    Gata4_chr14_5760             0
781458    2B2    Lamb1_chr12_2289             0
781459    2B2               pgk1P             3

[133704 rows x 3 columns]

In [ ]:
counts_df = load_example_data(
    modality="raw_counts",
    dataset="synthetic",
    debug=False,
)

metadata = load_example_data(
    modality="metadata",
    dataset="synthetic",
    debug=False,
)