In [1]:
%load_ext autoreload
%autoreload 2
import scMPRAforge as scm

2025-08-19 12:58:26.312988: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-08-19 12:58:26.317170: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /vast/palmer/apps/avx2/software/code-server/4.91.1/lib:/vast/palmer/apps/avx2/software/gettext/0.22.5-GCCcore-13.3.0/lib:/vast/palmer/apps/avx2/software/libiconv/1.17-GCCcore-13.3.0/lib:/vast/palmer/apps/avx2/software/ncurses/6.5-GCCcore-13.3.0/lib:/vast/palmer/apps/avx2/software/libxml2/2.12.7-GCCcore-13.3.0/lib:/vast/palmer/apps/avx2/software/XZ/5.4.5-GCCcore-13.3.0/lib:/vast/palmer/apps/avx2/software/expat/2.6.2-GCCcore-13.3.0/lib:/vast/palmer/apps/avx2/software/cURL/8.7.1-GCCcore-13.3.0/lib:/vast/palmer/apps/avx2/software/OpenSSL/3/lib:/vast/palmer/apps/avx2/software/zlib/1.3.1-GCCcore-13.3.0/lib:/vast/palmer/apps/avx2/software/GCCcore/13.3.0/lib64
2025-08-19 12:58:26.317184: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

In [2]:
import pandas as pd

## Test wald test

In [3]:

#create dask cluster
from dask.distributed import Client, LocalCluster
cluster=LocalCluster(n_workers=10)
client = Client(cluster)

path="/gpfs/gibbs/pi/reilly/tabula_data/shendure"
name="ortho_primordial"

import os
if os.path.isdir(path+"/"+name):
    print("[+] Model found. Loading...")
    primordial=scm.ortho.load(client,path,name)
    shendure=primordial.training_data
    primordial.precompute_wald(client)
    # primordial.save(path, name) 
else:
    print("[+] Model not found. Creating...")

    #load data
    data_root="/gpfs/gibbs/pi/reilly/tabula_data"
    shendure=scm.scMPRA_data.from_tsv(f"{data_root}/shendure/shendure_counts_grouped.txt")
    
    shendure.set_negative_controls(["minP","noP"])
    shendure.set_reference_cell("Pluripotent")
    shendure.ortho_filter()

    primordial=scm.ortho()
    primordial.criss_cross(client=client,
                       dat=shendure)
    primordial.extract_params(client)
    primordial.precompute_wald(client)  
    primordial.save(path,name)

[+] Model found. Loading...

In [4]:

# Wald tests now hit the precomp cache automatically:
test_fn = scm.build_wald_test_fn(primordial, shendure, cre_mode="vs_reference")
runner  = scm.HypothesisTester(test_fn=test_fn, test_type_name="wald")

In [5]:
# by-cell-type: test many CREs in NeuroectodermBrain vs the 'reference' negative control
hs_ct = scm.make_by_celltype_hypotheses(
    comparison_cell_type="NeuroectodermBrain",
    counts=shendure,
    comparison_cres="all",          # or a list like ["CRE1","CRE2",...]
    reference_cre="reference",      # this is how you labeled minP/noP
    meta="emvar_screen"
)

# by-CRE: test CRE123 across all cell types vs the baseline cell type
hs_cre = scm.make_by_cre_hypotheses(
    comparison_cre="all",
    counts=shendure,
    comparison_cell_types="all",    # or a list
    reference_cell_type="reference",   # will default to counts.reference_cell_type if set
    meta="cell_specificity"
)

# all CREs within each cell type, vs the 'reference' negative control
hs_all_ct = scm.make_all_by_celltype_hypotheses(
    counts=shendure,
    reference_cre="reference",
    meta="emvar_screen",
)

# all cell types for each CRE, vs the dataset’s baseline cell type
hs_all_cre = scm.make_all_by_cre_hypotheses(
    counts=shendure,
    reference_cell_type="reference",  # will be normalized to 'reference'
    meta="cell_specificity",
)

In [6]:
hs_all_ct.to_dataframe()

,comparison_CRE,comparison_cell_type,reference_CRE,reference_cell_type,meta
0,Bend5_chr4_8175,Cardiomyocytes,reference,Cardiomyocytes,emvar_screen
1,Cdk5r1_chr11_12559,Cardiomyocytes,reference,Cardiomyocytes,emvar_screen
2,Col1a1_chr11_15322,Cardiomyocytes,reference,Cardiomyocytes,emvar_screen
3,Col1a2_chr6_77,Cardiomyocytes,reference,Cardiomyocytes,emvar_screen
4,Igfbp4_chr11_16711,Cardiomyocytes,reference,Cardiomyocytes,emvar_screen
...,...,...,...,...,...
1446,Txndc12_chr4_7973,reference,reference,reference,emvar_screen
1447,Lama1_chr17_7787,reference,reference,reference,emvar_screen
1448,Epas1_chr17_10064,reference,reference,reference,emvar_screen
1449,Btg1_chr10_9578,reference,reference,reference,emvar_screen
1450,Igfbp4_chr11_16694,reference,reference,reference,emvar_screen

In [7]:
hs_all_cre.to_dataframe()

,comparison_CRE,comparison_cell_type,reference_CRE,reference_cell_type,meta
0,Bend5_chr4_8168,NeuroectodermBrain,Bend5_chr4_8168,reference,cell_specificity
1,Bend5_chr4_8168,ExEndodermParietal,Bend5_chr4_8168,reference,cell_specificity
2,Bend5_chr4_8168,EpiblastPrimitiveStreak,Bend5_chr4_8168,reference,cell_specificity
3,Bend5_chr4_8168,SurfaceEctoderm,Bend5_chr4_8168,reference,cell_specificity
4,Bend5_chr4_8170,EpiblastPrimitiveStreak,Bend5_chr4_8170,reference,cell_specificity
...,...,...,...,...,...
1240,ubcP,NeuroectodermRostral,ubcP,reference,cell_specificity
1241,ubcP,ExEndodermParietal,ubcP,reference,cell_specificity
1242,ubcP,Haematoendothelial,ubcP,reference,cell_specificity
1243,ubcP,Cardiomyocytes,ubcP,reference,cell_specificity
1244,ubcP,ExEndodermVisceral,ubcP,reference,cell_specificity

In [10]:
wald_by_cre = runner.run(hs_all_cre).to_dataframe()

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [13]:
wald_by_cre

,comparison_CRE,comparison_cell_type,reference_CRE,reference_cell_type,meta,test_statistic,p_value,fold_change,flattened,test_type,bh_p
0,Bend5_chr4_8168,NeuroectodermBrain,Bend5_chr4_8168,reference,cell_specificity,NaN,NaN,NaN,False,wald,1.0
1,Bend5_chr4_8168,ExEndodermParietal,Bend5_chr4_8168,reference,cell_specificity,NaN,NaN,NaN,False,wald,1.0
2,Bend5_chr4_8168,EpiblastPrimitiveStreak,Bend5_chr4_8168,reference,cell_specificity,NaN,NaN,NaN,False,wald,1.0
3,Bend5_chr4_8168,SurfaceEctoderm,Bend5_chr4_8168,reference,cell_specificity,NaN,NaN,NaN,False,wald,1.0
4,Bend5_chr4_8170,EpiblastPrimitiveStreak,Bend5_chr4_8170,reference,cell_specificity,NaN,NaN,NaN,False,wald,1.0
...,...,...,...,...,...,...,...,...,...,...,...
1240,ubcP,NeuroectodermRostral,ubcP,reference,cell_specificity,NaN,NaN,NaN,False,wald,1.0
1241,ubcP,ExEndodermParietal,ubcP,reference,cell_specificity,NaN,NaN,NaN,False,wald,1.0
1242,ubcP,Haematoendothelial,ubcP,reference,cell_specificity,NaN,NaN,NaN,False,wald,1.0
1243,ubcP,Cardiomyocytes,ubcP,reference,cell_specificity,NaN,NaN,NaN,False,wald,1.0
1244,ubcP,ExEndodermVisceral,ubcP,reference,cell_specificity,NaN,NaN,NaN,False,wald,1.0

In [8]:
wald_by_ct  = runner.run(hs_all_ct).to_dataframe()

In [9]:
wald_by_ct

,comparison_CRE,comparison_cell_type,reference_CRE,reference_cell_type,meta,test_statistic,p_value,fold_change,flattened,test_type,bh_p
0,Bend5_chr4_8175,Cardiomyocytes,reference,Cardiomyocytes,emvar_screen,10.714203,0.000000e+00,23.673172,False,wald,0.0
1,Cdk5r1_chr11_12559,Cardiomyocytes,reference,Cardiomyocytes,emvar_screen,6.058773,1.371636e-09,4.730881,False,wald,0.0
2,Col1a1_chr11_15322,Cardiomyocytes,reference,Cardiomyocytes,emvar_screen,2.119463,3.405135e-02,2.571112,False,wald,0.0
3,Col1a2_chr6_77,Cardiomyocytes,reference,Cardiomyocytes,emvar_screen,-0.268368,7.884163e-01,0.879807,False,wald,0.0
4,Igfbp4_chr11_16711,Cardiomyocytes,reference,Cardiomyocytes,emvar_screen,0.883484,3.769747e-01,1.554059,False,wald,0.0
...,...,...,...,...,...,...,...,...,...,...,...
1446,Txndc12_chr4_7973,reference,reference,reference,emvar_screen,29.942444,0.000000e+00,11.885299,False,wald,0.0
1447,Lama1_chr17_7787,reference,reference,reference,emvar_screen,-5.679197,1.353289e-08,0.133550,False,wald,0.0
1448,Epas1_chr17_10064,reference,reference,reference,emvar_screen,-4.859352,1.177709e-06,0.326999,False,wald,0.0
1449,Btg1_chr10_9578,reference,reference,reference,emvar_screen,30.837136,0.000000e+00,38.551599,False,wald,0.0
1450,Igfbp4_chr11_16694,reference,reference,reference,emvar_screen,-3.186711,1.439003e-03,0.464396,False,wald,0.0

In [13]:
some_ct = next(iter(primordial.by_cell_type.model.keys()))
Xnames = primordial.by_cell_type_design[some_ct].result()["nb_regressors"].columns.tolist()
print(Xnames[:10])

['Intercept', "C(cre_id, contr.treatment(base='reference'))[T.Bend5_chr4_8168]", "C(cre_id, contr.treatment(base='reference'))[T.Bend5_chr4_8170]", "C(cre_id, contr.treatment(base='reference'))[T.Bend5_chr4_8172]", "C(cre_id, contr.treatment(base='reference'))[T.Bend5_chr4_8174]", "C(cre_id, contr.treatment(base='reference'))[T.Bend5_chr4_8175]", "C(cre_id, contr.treatment(base='reference'))[T.Bend5_chr4_8179]", "C(cre_id, contr.treatment(base='reference'))[T.Bend5_chr4_8192]", "C(cre_id, contr.treatment(base='reference'))[T.Bend5_chr4_8199]", "C(cre_id, contr.treatment(base='reference'))[T.Bend5_chr4_8201]"]

In [18]:
primordial.wald_precomp.by_cell_type['Mesoderm'].result()

In [19]:
cluster.close()

2025-08-19 12:54:47,486 - distributed.scheduler - WARNING - Removing worker 'tcp://127.0.0.1:38321' caused the cluster to lose already computed task(s), which will be recomputed elsewhere: {'_build_wald_precomp_for_subset-16fba006802d086593596018d0b91390', 'lambda-3c5c6626eb14a21aa4c71d87f98bde82', '_build_wald_precomp_for_subset-bb53548833ee55a0fe2470741b529906', '_build_wald_precomp_for_subset-1bdbc9180eb70d0fcd525443d2dd505b', 'lambda-170cc010714afc9234ea68b7ae038e8f', 'lambda-1da1de772ff579bb0081dbf162129df9', 'lambda-227a306833d4432ba1173657f46f4ee4', 'lambda-43698d5f58f7120676089f39e3c39d9e', 'lambda-7f73e0dd085a2b415f5091783f258f6a', '_build_wald_precomp_for_subset-e359e60f52d4efc7dade4b7626966a0d', 'lambda-f5e78d3fb0303ceb707c08e5f3195bd0', '_build_wald_precomp_for_subset-1d922d7e2cc287845c2943f8d29b1213', 'lambda-4b8009dfcd8b45ef1d2e9aefce48d5d1', 'lambda-662c8e8f53f0d7e231ec8a79ee810360', 'lambda-f2d04477ba05dbb14908260904a3ec82', 'lambda-7458a8d97b427a3141d6b9bde008e622', 'lambda-c51a7f55266a213bd2dd9fe02c9b19f8', 'lambda-2504cb4f8376b2ba297e7e909057c653', '_build_wald_precomp_for_subset-ec65853597a4eeaca2f1275fbabaa08e', 'lambda-03b59b47174c4ea580aa9358149d8938', 'lambda-79e36c2ac92872ec81d355ce130fdf19', 'lambda-c97f1589978b57c61beff33fe27737df', 'lambda-1b3dd78155e8e75f84e1d1b53309ff7a', 'lambda-56ea714f176d2e0275667fcf163fb2fa', 'lambda-c59174be1ab28eb843883cda606dbdac', 'lambda-07db0a34e69f444336269ed7707dd13b', 'lambda-9a7ec096ec4a6b5740b10c390f97507a', 'lambda-03b49c35c5851aa6f67458a00803758e', '_build_wald_precomp_for_subset-5aa2802c90c57e1cdeef7e332857b802', 'lambda-5c2e7b4b5b8039e673aabfa14cf33ea2', 'lambda-4732f45f06220d6a7f846e3e7cb3079e', 'lambda-681696850b826186ff33bbb18bcc557d', 'lambda-52ff3a72b5aeac311a8a1926f142bf28', 'lambda-4d9757877195ba38b30ae60dc8f333f0', 'lambda-be669ae2f5f949bdedd4fddcd2672110', 'lambda-1f08ffb89abd2b34ac96af153ee7e2cd', 'lambda-91792c00c3200a7536a9af2c656f870b', 'lambda-3a0559854c9f13ee8ba8dfc3536f84fa', 'lambda-8b499c7e3c9503c5426299f38769eb29', 'lambda-19a77507943cee1e2fc9e5a2a6b2f407', 'lambda-4ed865ddae5728f7589ca053a06720f9', 'lambda-634dd037e4648b38aae9f92be8f860ed', 'lambda-513f0772b0cfbdfe0eddd5832c775ed5', 'lambda-3770d61f8a4486764426cb280685f279', '_build_wald_precomp_for_subset-c615256ca965f53822acdf271bc71a60', 'lambda-065cb5dfd938c6eb8a85a8dcc31ebeee', 'lambda-055b2ef320ff94d8cdfa02c3dd639ca8', 'lambda-931b9f50a3430ec71e25609df986fc53', 'lambda-6087462892858b08fe08bfd6a18c0433', 'lambda-c84ffc2fb1291e59c701c389d33c1092', 'lambda-905fb3046e6af7ea42854c9ec13760d6', 'lambda-6b9c2cc14461e57891ea8461cb27acf3', '_build_wald_precomp_for_subset-0060671c41fdc70483689a2a3c686f4e', 'lambda-331c83d1b50d57973c2a8781c6a448fb', 'lambda-9d1078f03f40566b66c5803840613af5', 'lambda-b94a4d66a2f7594639c8ecab1677d222', 'lambda-fd17a2e498e49ad63df796b81a64720b', 'lambda-1cdaf2d3371b9205eeee6085d99cc34f', 'lambda-e9344ed71ab70f5f34a0cd337ab6d0ea', 'lambda-cc192ad861a14d83230bcc0ee1062c1f', 'lambda-40c1f2d5274583dc36057837e3756f88', 'lambda-954d1740f6eb2d7cdb27a559347b83cf', 'lambda-5f5d9f155b13196b3585d32fafd41fd1', 'lambda-af44c77b98d10f4ae424f9b374cfa742', 'lambda-99c9c2b0ec55e85acbeade9ee23f8ce5', 'lambda-b0da9091b2aca475d537a96b44fd7696', 'lambda-ee023f9624d01e77ab5ed184a61d7215', 'lambda-35b74f0eb1cbd440e9e3ed2146fda43c', 'lambda-9ba2bbe230ad121269e1658bda6116ca', 'lambda-9d98ebb59c1b926dcf264038db7f115c', 'lambda-3cf46296fccf373f3f498751db6ed39b', 'lambda-2ab6b348f0951208a7997d50c4a4973f', 'lambda-caba9b0889d586e5794d0b08357a2e2f', 'lambda-b31c7d465331bbb080d58a9ea3bc3f09', 'lambda-73f616c1c33d5181baf602d4df54afff', '_build_wald_precomp_for_subset-07bbac35c729fd7519a67e1685a319c4', 'lambda-137318c6182400deeb2646375ff259ac', 'lambda-c92682b970228e19027715ce058bcf86', 'lambda-30f37fdfb1cb23cb2cd8faaa88504049', '_build_wald_precomp_for_subset-c2de377b2e11b26c8fee01f93baaf353', 'lambda-d7a6f6a518c1bcc5281bf2eb0b3e90ac', 'lambda-433283a0ad6ce8ed91ba5d54e087597c', 'lambda-596b032530df97614a1667ee15329960', 'lambda-af8e79e2272961f711320d5c260b764f', 'lambda-f8052ffac58a70cb5583ec71561de89e', 'lambda-60409f05bab1cacb9ba178287ef1604b', 'lambda-549c760fe7eb28e50590705ebb06eb25', '_build_wald_precomp_for_subset-6f6800dcf8c5e8175edafa9fda5112c5', 'lambda-354ed083bfdbb58dc957ab167b19628a', 'lambda-b9d0f3ae7c8ecfb380c23bc0a79ff7a6', 'lambda-91cdeb18262f3c23e8ca1d02fad9d2ec', 'lambda-83eed32ef61a9b886bfce1059b3b19fd', 'lambda-6df5d6d5a19b4987e8ef86b5ef19b908', 'lambda-72be91d8932945f7c7e9e5980bc7b2cb', 'lambda-39e57f576be4e1b9df1f4cf18db283c4', 'lambda-15ac12a9bb4661d5793a6faa7289c025', 'lambda-3596ae93046b5aa7f7a2907943bb3318', 'lambda-c48e6c3b27518e2b913c147c744ca706', 'lambda-333ea69dcfd202bc5ae82a579085f6ec', 'lambda-b8c5024887c478be42d23ac425211fbf', '_build_wald_precomp_for_subset-bd47b9bcc0bb612ded7be53c30a4a0c6', 'lambda-8393831745c1e853fc1bb6b1909f2fb5', 'lambda-102759037b20fd28fa20f80715956801', 'lambda-b320d6f83d57cf10991c190a2fb2e7a2', 'lambda-6ce8bbe8b8f75779b531683c52c05afd', 'lambda-56fac03f6b9f4d28ccac13ad441fc5cb', 'lambda-0520f322588eebda987cdb32ae0bfb9e', 'lambda-53359fb69b58636ec49c4754d4f4f26d', 'lambda-0e07be3a3545de52b6d75f679d3a5c53', 'lambda-d6dc40fedd8f6e20e1c74ee65d7fb83d', 'lambda-a28ba95cf7ece7d12e5a8349557587a9', 'lambda-cb41fb635c5d07e4bb4faaa5eb581934', 'lambda-75db27d13591a33709385e608940fa72', 'lambda-389cfe10fb71f5ed7c0cc2ec998fa09e', 'lambda-582d999b845bfbffc94bdfe3deb10d26', 'lambda-518c283b8883dc790d8a6fa30cd79f1f', 'lambda-ab178b11994ff6b17ad51cb29d7ecb87', 'lambda-f74a0d4b1afc842c6c03eebceff7a6a0', '_build_wald_precomp_for_subset-f0b1870fe72967957120e791bae3bc18', 'lambda-3ca9e2536270dd5e01b882d4131883b0', 'lambda-f957a43fe5080d43f10b33c43618e940', 'lambda-099fe6ffe822839ca1bd3927a2848aee', '_build_wald_precomp_for_subset-94ba0c78baf094338666acb88bedf43d', '_build_wald_precomp_for_subset-f3e6a2a422700045796c5d9117a362e0', 'lambda-d002116694754dbea376c6f8a68c0a85', 'lambda-e28f6b326a0f7b3e84fc65c8dbe8389e', 'lambda-1e39836a4e4335f04fc65b1510781b64', 'lambda-3ca2ddb08321919c45ee59b20fd0a190', '_build_wald_precomp_for_subset-6a60f81ad43f4487ba796fa645f5a654', 'lambda-fe50490f136f4e23b426eb70a58e6b63', 'lambda-a59214f3b65083573c930f4e5196fb31', 'lambda-d08217e8ec21db4480f1ec55e53c7cf3', '_build_wald_precomp_for_subset-ede0f4b888ccc18b6ae40d4491af5c73', 'lambda-7568d9eb142b7e9b17ca82321ee23dee', 'lambda-526d93e4964903af38fcc6aafe2ec5d6', 'lambda-b60df041e77bdbca517686ccd27ce37a', 'lambda-d56b14427668b8e75479a65846a48202', 'lambda-876eeb93dddc61837c33d84a20f476aa', 'lambda-54e467794c8612aa3ced7bf56e29422a', 'lambda-221758b47e87dacc008c53e5dba6b6bf', 'lambda-0f205083a62aa80426a12ae512aafd41', '_build_wald_precomp_for_subset-842575ae0ce6be7dc33133051ab1fa1a', 'lambda-fffb2f641fed5394930cac7224e7d637', 'lambda-563f2ad903fcaae7935fbbdede8d3016', 'lambda-3aef8108c0cdc003c63142ef6e690bec', 'lambda-7dc0f63c7249a97b95c66de6c88a7167', 'lambda-fff200e6716c5810550ed771539a8e74', 'lambda-a37db7f2043edb6f42317288aedf566a', 'lambda-0a75332205232edea33deecda1ef10ea', 'lambda-17b33323eb141919d1a0912554aeeec3', 'lambda-b7409919c73dadb8e331ad992fe58aff', '_build_wald_precomp_for_subset-3eb885bda059b7c306fb2761a3dd0fd3', 'lambda-9643cd0a1aea1353a1e4efabe1bc13b0', 'lambda-236e6c0784ebf87385ab6a6e6199da6e', 'lambda-28ccbd1ac263cd361a27287e43d06ddd', '_build_wald_precomp_for_subset-d13e888b889ea276bf609071bc11e72a', 'lambda-6ab998e0f424c2955cbf567aaaa23717', '_build_wald_precomp_for_subset-c25496ee2192f450f51a9a7095af1d50', 'lambda-d76b473ca34d74c2dbac8b3fab4b0bf2', 'lambda-45d0078bb49316e9ec6b4906203d98c3', 'lambda-782a8b795dce68baafa21e11f1c6424f', 'lambda-f415d304f900ee6d23f4e3361dd70651', 'lambda-8772206b8151ddaf93f74c755ff886ed', 'lambda-4f45833500045de9f4da898caa15feab', 'lambda-3ed65dce34e77cd556caf07df9be18bb', 'lambda-92d8157ab97fc3206054b736c1b7a6d9', 'lambda-38aafb3b4ca567812452e50ccf178d2a', 'lambda-d2dc879193659589c42cfea7efb861ff', '_build_wald_precomp_for_subset-608015ea9209eecaf3b5f434010a51cc', 'lambda-28680c2d56f4b1bd2751c921b6441ae6', 'lambda-8774a61baa4de7ab5ea033b430b4e4cc', 'lambda-4a3841f41cb892793160fa1858846d31'} (stimulus_id='handle-worker-cleanup-1755622487.485967')
2025-08-19 12:54:47,531 - distributed.scheduler - WARNING - Removing worker 'tcp://127.0.0.1:36279' caused the cluster to lose already computed task(s), which will be recomputed elsewhere: {'_build_wald_precomp_for_subset-0b9d3871e6986941bb04652fe4aba4c1', 'lambda-def71f60899899a9e899c891e3e8eed9', 'lambda-1693ceecf96e46b193f89dcdd7506271', 'lambda-1413956f23391d356873e48a48dd1c21', '_build_wald_precomp_for_subset-4a1889e1e214bcf246bb961f91bf5d98', 'lambda-d67d1e6b71c676be6639b311cffec97a', '_build_wald_precomp_for_subset-62deb4333553ea4026170c098e1bc9d8', 'lambda-40ddb3d09796cf103cc382631ca7b92f', '_build_wald_precomp_for_subset-7d041aa207f6e0d471824ab15f203841', 'lambda-65deef2182c74081a1721cc6777a5283', 'lambda-662619021cfcd8585b8abdb4f4ebd79b', '_build_wald_precomp_for_subset-a536ec3845c229ceaa79e2d3143ba9ef', 'lambda-7757a8e3af7e1a914742db527bacd748', 'lambda-46a48c8930cf1f9f7d4cd69b5247c9fc', 'lambda-b5dec41ed7ad42fc74deaa5f33b0e384', 'lambda-19d9b11c9a80863afc03c36db7c42c8e', 'lambda-28d4aabdbac80710406bf6017fa6728c', 'lambda-aa04bdc545e04d8737c2ccfec2c7dc96', 'lambda-f3e4dfaacc199895453d03455041ab90', 'lambda-0cc89565629bedf20840e212aebfc485', '_build_wald_precomp_for_subset-ee4544478c90fa74bacf1c1c6fcff326', '_build_wald_precomp_for_subset-1633c8dc3032dfa2612e71b9264589a7', 'lambda-503175a9fded6242b0a9775728188115', 'lambda-00d81b5473ef06626cc0d4af1d96431e', '_build_wald_precomp_for_subset-1e45c12fbc87bb057d5a6cc8b0358c26', 'lambda-31b5a4c0b5e8e77beca4f95fd403f606', 'lambda-49f0c9665b6248d0dece2078c9b500df', '_build_wald_precomp_for_subset-d3eb1cfeb2609cf7491ec454035260d6', 'lambda-078de3c0e681e8c05ec758a322db11bb', 'lambda-28fbb117ec6e1c079b3564eb38cf7e0e', 'lambda-a3d7300e1fdcff9e972c9bde4f84670a', '_build_wald_precomp_for_subset-fbf3721049f6322d9943220860ef77bf', '_build_wald_precomp_for_subset-70120a1c042c31089fd0d20b536d7946', '_build_wald_precomp_for_subset-0e5da7e354df416548ea5e401682518b', 'lambda-3fc71b878a6168b52402275cc990657f', 'lambda-bef338cc4a4815f9909860f08010f79c', 'lambda-21064ddabcc5cc6b2be76a7953775352', 'lambda-37a15f2b7c8ab5fb78fb7d0094399436', '_build_wald_precomp_for_subset-6d813a54958ed8e13a5c0b760a018e7f', 'lambda-bd86a2d02c61dfea5194ebd1d95e8d17', '_build_wald_precomp_for_subset-3872b5632ad24fd54ade588b7d85c4e7', 'lambda-ec2e3479c4dd8b2c11311163e5df7ed1', 'lambda-827b21ecc58df134299f061a30633516', '_build_wald_precomp_for_subset-68d9df2e7576fc628e937bd3290a52c8', '_build_wald_precomp_for_subset-6ffe07799ad4542c78612edf45861457', 'lambda-77939af817ad0031764811c76a8ce85e', 'lambda-03a7a5a8c289e2618081de640bea01ba', '_build_wald_precomp_for_subset-1f340258eaef2004fa961c892c2c542a', 'lambda-a38685c8b43cab1b29a559bb14b9eb41', 'lambda-d62a7385656f1d63595f8f9c648d01b0', '_build_wald_precomp_for_subset-84209a2f3c0631a83d1309e706703b4d', 'lambda-a06fcb31bd974ceecefde22dfc0604b6', '_build_wald_precomp_for_subset-b2e1563e57a15f1a158f2637b3d6b0d2', '_build_wald_precomp_for_subset-e11b49dd332ae5ccafe359832f49dde9', 'lambda-137800a34d0087c721b8d9109066dc5b', 'lambda-741bcbcb7ffd99fef107e13372386cd9', 'lambda-8a45a5aa9f9e5c8f40b0d22a0c01a938', 'lambda-f70dcbd842736ab9837a548d3b0d9da3', 'lambda-e4e527950c5a89354f31ce7cf4860983', 'lambda-e184a2585e41c5979b1cebe4ccaa0d71', '_build_wald_precomp_for_subset-90ae39f48e89719e36c9b518f3169d07', 'lambda-4ebbdc3e66ef18ecb329724165056581', '_build_wald_precomp_for_subset-8aa9f7e6f6bb35c0ad654da7e0fc3ad4', 'lambda-eb90e09f37bcbed8f3774c5d89fa58d1', 'lambda-6168b132dc73356c0302309a7ae078b9', 'lambda-5c7938b3f2fb8eaff33c78d6fc0f4b8f', '_build_wald_precomp_for_subset-04b994f8b80f39386c10d5fbca4fca22', 'lambda-714ba9e9a94046a76628465aedce943e', '_build_wald_precomp_for_subset-44c3b60579cd9e59d5b17015607c5885', 'lambda-fd8eed7a5237e93bf1cdfbabd169544e', '_build_wald_precomp_for_subset-490a41dfbf0adfc06ae37dc1ed7aee81', '_build_wald_precomp_for_subset-91ef862fa5b5dc3cea3caffe7035c6ac', 'lambda-085224ea6efb71060bdb07980d25839a', 'lambda-883458225b0c565ffb3bda92bc7f9ea0', 'lambda-b2757b55906b44e61503d5c6075fda3f', 'lambda-16aa0a681cfbf30a6ef6f1b66d764277', 'lambda-170991d57450988149f860e8af55aa88', '_build_wald_precomp_for_subset-ece555f65b1ee52482388a2fd3e573d0', 'lambda-93b6208b79209b5ad15ac9759b5040b6', 'lambda-fb187bd795937ce82694e25c368dbe7f', 'lambda-81120b34a588becdac03c6cd815738f0'} (stimulus_id='handle-worker-cleanup-1755622487.5311043')
2025-08-19 12:54:47,578 - distributed.scheduler - WARNING - Removing worker 'tcp://127.0.0.1:40177' caused the cluster to lose already computed task(s), which will be recomputed elsewhere: {'lambda-d2f4491330097ddace07ab3a6ca1bd51', 'lambda-850dd21116804e474b413f00f5147407', '_build_wald_precomp_for_subset-b4d5e4a25cae61bbe7eab31ca8cc773a', 'lambda-398709f1f2f1e069561d993125c584b7', '_build_wald_precomp_for_subset-3acffa9cc5d4fa50bd2e51caea58a433', 'lambda-ab32d0c278ec241306b5eb61602d2232', 'lambda-14bb83aee827228c43b6bcf8a3535272', 'lambda-8b143161a7a5879b1748f41232c1e1f9', 'lambda-a39dbca28202e7bfa25aa9805dbfcbf6', '_build_wald_precomp_for_subset-869539c3943f712b52fce78d7fdceb21', '_build_wald_precomp_for_subset-886c52158926231c640cb970c0f0bd15', 'lambda-c17c552265c5bf55de2e24e70f3c7b96', '_build_wald_precomp_for_subset-ce44201c8cc74ee08969f1d801f7187d', 'lambda-dd52296b100e960ea76d8eeb4f76f73c', 'lambda-cea53d47324172d2c82d7a92ebfeec3a', 'lambda-faa02a4f9ed1083079b9a9b7eccb1b10', '_build_wald_precomp_for_subset-ac73e9ac274330effaf2b59a3fbd067c', 'lambda-9f8f09992353aa3d153fc411c5541002', 'lambda-de7e05dbc7ca91dfd05210d88abe0bbb', '_build_wald_precomp_for_subset-7e169b67fe0d3f74be8bbfd64d5209de', 'lambda-c30c54c3112e51a49f0262dc888aff75', 'lambda-a1c0fffe556db46430488791e43a749e', '_build_wald_precomp_for_subset-bff116b9d45c0f2974a86711b3476f8c', 'lambda-27725cb34bbcd658fcdcd72e7b070d1d', 'lambda-0d26b8cb186f6dcd79bafc534ddc23f0', 'lambda-34a9ea093a842c10f8225bddab7e61d0', 'lambda-6998d36bc8a0d081823c7eba3db465cd', 'lambda-1779593666f841d35b61754affc6b3fe', 'lambda-51c3bc712af14df7eff1248075159c4e', 'lambda-92db3793c757ff49ce2873c051bf5ba3', 'lambda-277113d2bf026b55fab78ef2967379a5', '_build_wald_precomp_for_subset-c2572d86c3aac9238c42401e2526c98c', '_build_wald_precomp_for_subset-17f9650bfa80fe4d5f9660236885ada1', 'lambda-ae9e10f87b264a3a09a77431fe4508e1', 'lambda-08959df0aec7f30bb6463c6d0d91c3db', 'lambda-b406e0ebabf607f2db5b999f52d8b0ed', '_build_wald_precomp_for_subset-b0f6e37e67d8c9e9de27eecc37f364a8', '_build_wald_precomp_for_subset-be080ebf6257b97bbfa345bd2254b0c6', 'lambda-8304103093ae64e207879810efa40b7e', 'lambda-cd978bcd5baab4824e7c629e4d6fee89', 'lambda-335cf6ac8e279b9833ebe51ab4438e44', '_build_wald_precomp_for_subset-954c78d8e5c08ba046721373a1d57896', '_build_wald_precomp_for_subset-f92f17272f3f097bb86c1f50bf4bb1eb', '_build_wald_precomp_for_subset-048ce138e8dd90361eaf2aa2c7940326', '_build_wald_precomp_for_subset-33b5cd4d8e72ea0f183d943ceec724fc', 'lambda-5df305b5b147484b4dc3d435500a6a69', 'lambda-be334048bf1a7eb55ea3ba01275d99e1', 'lambda-799ec5d48883f5e492917f894e55dd9d', '_build_wald_precomp_for_subset-d733f00b96fdbff6d7450f2ff9bba430', '_build_wald_precomp_for_subset-dc2933c5f8672b995f5afed07382e56c', 'lambda-b8da89432c15089433acca55fe8da998', 'lambda-9ebb450b0956f4026f9262a4375dc2e4', '_build_wald_precomp_for_subset-05c2114410f5c85d199d0029c1b8da5a', 'lambda-bf032b53da2d431f3c55c57c0da44b1e', 'lambda-7d09c94901ea53b91efd74d394db03e6', 'lambda-e9f2fd6b6ef672c83ba1c88585fbde78', 'lambda-a7c11dbc44769768592d78de06901153', 'lambda-206bc673765509906467bf767faf577f', 'lambda-555d29fe6a94171c330c60825576fb64', '_build_wald_precomp_for_subset-97e50efa18019b14b87524d5ee56dba0', '_build_wald_precomp_for_subset-d02e1a26f1839e5e3d2134329a297177', 'lambda-0c8e6dfc453a417384452321db3950f8', 'lambda-059eb0cda739c6fb515fd989bccc206c'} (stimulus_id='handle-worker-cleanup-1755622487.5782928')

In [10]:
import numpy as np

In [13]:
np.exp(3.1643424)

23.673171435586262