Creates a very basic de novo simulated dataset, with a more realistic ratio of true positive to true negative than `simple_spread` provides.

This is similar to `simple_de_novo_simulation.ipynb`

# Imports

In [1]:
import sys
import os
import scMPRAforge as scm
import pandas as pd
import numpy as np
import dask.dataframe as dd
 

%load_ext autoreload
%autoreload 2

2025-09-12 18:16:42.251570: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-09-12 18:16:42.255675: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /vast/palmer/apps/avx2/software/Code-Server/4.17.0/lib:/vast/palmer/apps/avx2/software/gettext/0.22.5-GCCcore-13.3.0/lib:/vast/palmer/apps/avx2/software/libiconv/1.17-GCCcore-13.3.0/lib:/vast/palmer/apps/avx2/software/ncurses/6.5-GCCcore-13.3.0/lib:/vast/palmer/apps/avx2/software/libxml2/2.12.7-GCCcore-13.3.0/lib:/vast/palmer/apps/avx2/software/XZ/5.4.5-GCCcore-13.3.0/lib:/vast/palmer/apps/avx2/software/expat/2.6.2-GCCcore-13.3.0/lib:/vast/palmer/apps/avx2/software/cURL/8.7.1-GCCcore-13.3.0/lib:/vast/palmer/apps/avx2/software/OpenSSL/3/lib:/vast/palmer/apps/avx2/software/zlib/1.3.1-GCCcore-13.3.0/lib:/vast/palmer/apps/avx2/software/GCCcore/13.3.0/lib64
2025-09-12 18:16:42.255688: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

# Create cluster

In [2]:
from dask.distributed import Client, LocalCluster
cluster=LocalCluster(memory_limit='24GB')
client=Client(cluster)

# Seting experimiental design parameters

In [3]:
#first, we define the new parameters we want to assign to this object.

new_cell_number=pd.Series({"reference":1000,"blood":2000,"neuron":1000})

#we make up 3x replicates
new_zi=pd.Series({"replicate_A":0.02,"replicate_B":0.021})

new_min=1
new_max=200

new_MOI=60

In [4]:
#next, let's create a bounds object from these parameters and the bounds of the shendure data.
artificial_bounds=scm.SHENDURE_BOUNDS.copy(
    min_mpra_umi=new_min,
    max_mpra_umi=new_max,
    zi=new_zi,
    cells_per_cell_type=new_cell_number)
    
artificial_bounds.set_effective_moi(new_MOI)

# Creating an artificial library

`cat shendure_counts_grouped.txt | cut -f4,11 | grep "^minP" | cut -f2 | awk '{ sum += $1; n++ } END { if (n > 0) print sum / n }'`
Produces `0.0727759` as the average MPRA UMIs per cell for minP.

In [7]:
#making up the CREs
spread_gt,spread_hypothesis=scm.activity_spread(
    cell_types=list(new_cell_number.keys()),
    minimum=new_min,
    maximum=new_max,
    minp_value=0.0727759,
    total=1000,
    frac_active=0.5,
    ct_specificity=.2)

library=scm.simulate_library(CREs=spread_gt["cre_id"],
                 library_model=artificial_bounds.library_model)

scMPRAforge: INFO: 83.6% of active elements are not cell-type specific.

# Performing de-novo simulation

In [8]:
batch_plus=scm.de_novo_simulation(
                        simulation_replicates=3,
                        experiment_bounds=artificial_bounds,
                        ground_truth=spread_gt,
                        library=library)

In [9]:
batch_plus.gamut(client)

# Testing parameter recapitulation

In [10]:
test_data=batch_plus.simulated_scMPRA[0].result()

In [11]:
test_data.ortho_filter()

scMPRAforge: INFO: Dropped 126 of 2988 (cell_type, cre_id) combos with fewer than 3 nonzero entries.

In [12]:
primordial=scm.ortho()
primordial.criss_cross(client=client,
                       dat=test_data)
primordial.extract_params(client)

In [13]:
primordial.compute_model_qc()

regression error on inactive_268

In [14]:
cell=[]
for i in primordial.by_cell_qc:
    working=primordial.by_cell_qc[i]["dat"]
    working["cell_type"]=i
    cell.append(working)

cell=pd.concat(cell).reset_index()
cell.merge(spread_gt,on=["cre_id","cell_type"])

           cre_id          mu  mean(umis_mpra_bc)  cell_type  true_mean
0        active_0   60.722160           58.436681      blood  75.286722
1        active_1   41.149135           39.677966      blood  37.551817
2       active_10  106.513454          102.519582      blood  94.017972
3      active_100   68.185934           65.445652      blood  62.020999
4      active_101   15.309075           14.752044      blood  16.628219
...           ...         ...                 ...        ...        ...
2857  inactive_96    0.147987            0.142857  reference   0.072776
2858  inactive_97    0.075646            0.073034  reference   0.072776
2859  inactive_98    0.084906            0.081967  reference   0.072776
2860  inactive_99    0.072400            0.069892  reference   0.072776
2861    reference    0.092494            0.080645  reference   0.072776

[2862 rows x 5 columns]

In [15]:
cell=[]
for i in primordial.by_cre_qc:
    working=primordial.by_cre_qc[i]["dat"]
    working["cre_id"]=i
    cell.append(working)

cell=pd.concat(cell).reset_index()
cell.merge(spread_gt,on=["cre_id","cell_type"])

      cell_type          mu  mean(umis_mpra_bc)        cre_id   true_mean
0         blood   60.628515           58.436681      active_0   75.286722
1        neuron   70.028780           67.620968      active_0   75.286722
2     reference   79.890787           77.063492      active_0   75.286722
3         blood   40.095153           39.677966      active_1   37.551817
4        neuron  151.961331          148.900000      active_1  134.739033
...         ...         ...                 ...           ...         ...
2857     neuron    0.184022            0.114754   inactive_75    0.072776
2858  reference    0.096933            0.056604   inactive_75    0.072776
2859  reference         NaN            0.064935  inactive_269    0.072776
2860  reference         NaN            0.181818   inactive_59    0.072776
2861  reference         NaN            0.076923   inactive_65    0.072776

[2862 rows x 5 columns]

# Save

In [16]:
data_root="/gpfs/gibbs/pi/reilly/tabula_data"
batch_plus.save(data_root,"simulated/activity_de_novo")
spread_hypothesis.to_tsv(f"{data_root}/simulated/activity_de_novo_hypotheses.tsv")

In [17]:
cluster.close()

2025-09-12 20:04:10,099 - distributed.scheduler - WARNING - Removing worker 'tcp://127.0.0.1:32773' caused the cluster to lose already computed task(s), which will be recomputed elsewhere: {'_extract_theta-c4c10ce578269706cc58272397868aae', '_extract_zi-a66cd711717dfa2983ef8e0b564fa1b3', '_label_tensorzinb_regressors-07469c9a3bb2eba049b24fdce825ed9c', '_extract_zi-b4544105a655ffb80ab23c0925a19cb1', '_smart_matrix-a4d9f834601c614fff38f0ee99a6bf74', '_extract_zi-a0e46e99edb547fb788d7605efb631d6', '_extract_mu-2d85c7b2dbc2d411d27557c34dca23ba', '_extract_mu-e8ea39bdfc66180626f62d479ee9a7d1', '_smart_matrix-1a945fad6ae956a24f328d79c6f7026d', '_extract_theta-066d7b2b9cbc15ee62d3ca02ea33a2da', '_label_tensorzinb_regressors-56248f1b7b70b9829a480acd2bd6cbd9', '_smart_matrix-fc0a2a842a5b9ca6a6395d7840324889', '_smart_matrix-01b29c4b336bb5043ffd825497261faa', '_extract_theta-c265db77fa2c4a25109f72f246ebd909', '_smart_matrix-d15da3602d18a56486bbf9537630d13b', '_extract_mu-212026077ff494389be70591ba4cfcc1', '_extract_theta-b5d10ca29e569449c366481f0c70acf7', '_extract_mu-ec7d3f9dcef3521671034094dcedff7a', '_smart_matrix-970cf10b6b2b9c184253ae6eb8ab8f08', '_extract_mu-436212427c6f520dd704d9b385a1317a', '_extract_mu-f9ce9dca1da9212451ff9bf09ef593ad', '_extract_mu-55740b4e13690a69eccc22574ddbcb09', '_label_tensorzinb_regressors-6b0ff9df8bc5dcd9f1b62c77b1995f5d', '_extract_zi-cb8fa6719dd82c1f12ff5b3586d6b0b8', '_extract_theta-689d8ab640fbb79ddc950e7b2c3ab440', '_label_tensorzinb_regressors-0370ad039ef994afa19811947df889f5', '_smart_matrix-7086dc48bff9bb469602a6a3e192a199', '_extract_zi-93e0d9d874dbba65d5656805bf67c2c5', '_extract_mu-5dad6bbf91b38a6f69bd27fd9f4c4ade', '_extract_theta-0b0199861d34854b669125baa55b748a', '_extract_mu-69d19072387c211ef0953d35b039022f', '_extract_theta-504c038aac617baeabd6035de7d7ac58', '_extract_theta-436eb9ce3bfa807b7c4344ae37277760', '_label_tensorzinb_regressors-c69589f3f3003003a53144967978e7c7', '_extract_zi-e7fbc6ef15def1fe45c50bbb4d327a6c', '_extract_theta-9b551b98133649a496e36aeaba09722b', '_smart_matrix-d974d21674e7dad98dacb5433b536987', '_extract_zi-2e0da02bdfc182353cb6c31ded09f095', '_extract_mu-967e8f5b47d2e650cdffeefac0a37ac0', '_label_tensorzinb_regressors-43ab7eb524e53c714d6478edddc341b0', '_label_tensorzinb_regressors-9d1605acf27f00ede0ef8019191fd9a0', '_extract_zi-b7f15b4b241682514fe9898eb7bdb73a', '_extract_zi-fecfda022e9ebabf0355424cd96dc7b7', '_extract_zi-36b18a5ad256f98fff6964cc98f34838', '_extract_theta-0b9f446c282e159b8dc41e635365eb3a', '_label_tensorzinb_regressors-a928d1c8e994f25e420783b7e1afd13b', '_extract_mu-ba88236ce451cffb4c52995042d8e943', '_extract_zi-f3929710684646f3d5c5a55a6e41bab9', '_label_tensorzinb_regressors-7d190d159302a436b363627c967517ef', '_extract_mu-8bc96f4cf26e00ffb04ccbc3994263b2', '_extract_mu-5e82cabeed2707dbe0c050f0098a14b6', '_smart_matrix-e7050416afc8e2fa0ad480acfb2c2ec1', '_extract_mu-88bdde7b3558baf0895a63b5ce994d86', '_smart_matrix-35169f5896a7b43b9cf07ce02f00034a', '_smart_matrix-c72bb15418e83e47fab5a49e6ca46477', '_extract_theta-b5ce6484045e4e2a899a4626b5b0f941', '_extract_zi-c0a235adf37e44d41b5ab5854c43715a', '_smart_matrix-0964fd70c6a9ba6a57388677550b3da9', '_extract_mu-b578b099be17241b512f93daa5b92219', '_extract_theta-910fecc5bf6d9c2f8e1a8491c41ed514', '_extract_mu-ec5aed394db8c01c13f80255505b9209', '_extract_theta-2abfc4434e569861585084160bbc3d03', '_extract_zi-e2916295744393d47fee46f125e7d30f', '_extract_zi-46bdcf4493e4489ac641302adcda8030', '_smart_matrix-7c57a306e90787ec8bcae68f8af0355b', '_extract_zi-510c73a9194d8ac7175dfd08efdb90be', '_extract_theta-5f2581995f2fee3813dcfb94659caeb9', '_label_tensorzinb_regressors-d84f9389951954e6b2ae1e92611578b3', '_extract_zi-f5ccfe674aba26a3a9f63bcd620e850b', '_label_tensorzinb_regressors-2c25dc327acb3054565401f01e9dfdf7', '_extract_theta-7ce73855305833b2c0170edbc14a8f9a', '_label_tensorzinb_regressors-89e7bad07ed0c701cb3573ae30899192', '_extract_theta-5fd3e8939bb78f3a7169fa149fadeb78', '_extract_mu-37df8b6c591724f6531deb37aa08016a', '_smart_matrix-6f9f4f8cbc733c4a5d69b9fb9d0970f3', '_extract_mu-5ce77ae527c0b749cbabc5f6f2ac808d', '_extract_zi-18bf879bead230ad4f993c64b23e7c36', '_smart_matrix-2e0e7e2947f1fc99e6058510a8356514', '_smart_matrix-a3cb67292b1dcf4edc94ac47e1349370', '_extract_zi-e4760ad4ccc8bc280db8c33089322d3a', '_extract_mu-3e216b37890a93011e4ecf450e2e4570', '_smart_matrix-bbd91ba2aa844f9a1256954017e12c6a', '_extract_zi-89ddfd71ccfb440305bb81421f00e56d', '_smart_matrix-a3dfb00c69606ed2e998a8915c0d3b01', '_label_tensorzinb_regressors-30c4550d12bce4e441f6e18e7d1eaed3', '_smart_matrix-a7eeb8139dfc64964dd3b4bc75cb60ff', '_extract_zi-377565168b02330afdd1ed25e6775c8a', '_extract_mu-526266ecb21a56f2363f610d963c733d', '_smart_matrix-19f68073cd44ff9fa3af05ce803e08e5', '_smart_matrix-7729181963d3e70eb808720193728f53', '_extract_theta-a5c4e56598d6bd09b4cc5ab9b8f714c1', '_label_tensorzinb_regressors-62c7033ca5b364ad34c82be7761fd5a9', '_smart_matrix-8b0cf25aba1666afb63e209412255488', '_extract_zi-01d0b273e8d466e9bf04a5ae377ae254', '_extract_zi-920bbb354b06f7a1e55e506d3fa25d79', '_extract_theta-fbebd98c5da5ee63540cb3aafcb4f21c', '_extract_mu-b8c6fbf5ae40ef91204e022e91dbe10f', '_label_tensorzinb_regressors-3fc250c08f8993c17c3074645c115ee5', '_extract_zi-301cde2cd7e11027c85213ddb36be25a', '_extract_mu-eabfe5def66bd46b20aa0a06ea3f9b0c', '_extract_mu-3a134e9158145e86450fc36dec202654', '_extract_zi-2544aef88432550df4dd6a71851da663', '_extract_zi-a240ff14fbe878c247eca212bd058554', '_extract_zi-082c5c9a49175fd0b99d7a55f120b958', '_extract_zi-cadf1a577529799ddd89a00e19060d66', '_extract_mu-119bd305e1e792e3fcc0b5a31166768b', '_extract_zi-a1bb86298020c38d4d39fb167bf09ad4', '_extract_theta-89fdc571dbcf084a006c3329ef9583ec', '_label_tensorzinb_regressors-b367c6a0c3891415f80811cd1cfb5daf', '_smart_matrix-b2c5777526119e5f6fe4dfac8215fb22', '_label_tensorzinb_regressors-631b71754afc7550f6cab139d40de7bc', '_smart_matrix-384947e433a89608ed07c36e42c0d2ec', '_smart_matrix-e78f8cee1666d34b2992f892b58d6386', '_extract_mu-c316f52fc4a413d93d67b3909f12eccc', '_extract_mu-022037f28b175fe3e83378c5f8f766e5', '_extract_zi-2611f45a54f4f2d1c190e02d0e86b5a4', '_extract_zi-6f208025546a8962be7920f3e9abe55f', '_extract_zi-2447587ffde886d6df9ebf664289343e', '_extract_mu-c454b83cd8cdc9d586455aae83358f82', '_extract_mu-c044872551eadbd81fae0ccb85a876d6', '_label_tensorzinb_regressors-79f80ce7c4701a60959cd58fa3a6b538', '_extract_mu-2b8de19c14c1fa7e29f6c6856915a8f0', '_label_tensorzinb_regressors-c99bc492cc6eaf6904a7eb53e5ec5f92', '_extract_mu-e2d965e221fe250f5c3e9e8128190650', '_extract_zi-364c701377e8062da6528129ee6f27fe', '_extract_zi-cbcdbac36bb345636379be17b317ca80', '_extract_theta-ac4ab15f373ac9f6afb2f922a35d55c9', '_smart_matrix-6f6b2538517e946c95a36024386817b4', '_label_tensorzinb_regressors-80925d6a063010189f35f4a0c3a1b7b5', '_label_tensorzinb_regressors-0ad012d43e3a979d72e6dfc9d7360fc7', '_label_tensorzinb_regressors-c72ffa589d0eba294435d71a5e9d0a2d', '_label_tensorzinb_regressors-1336ff486ada87e672fcb298364e2f97', '_smart_matrix-0c0e8b4e6fe60c8db18b026c66356180', '_extract_theta-f4babc58ae0f13081b9b93dd38af1e04', '_label_tensorzinb_regressors-ec0328b0f0ea3c5a54614c93bf9ed2fe', '_extract_mu-ed07a150e4c7e77547e4dac84b705581', '_extract_mu-f42bf9ece4e47d65a063e95f53b1e184', '_extract_zi-962aeb2d744b51aeb42225ae32f2e04a', '_extract_zi-874c82ff458b3127bbe96cf33fe1c049', '_extract_theta-7801ccad222e0236c0c75be648eb3a1e', '_extract_theta-856649312656bce1570bf137f9a38911', '_smart_matrix-ab84de61005bb374feee182b1d152904', '_extract_zi-339b96d549cd0ea1de5086a10cd4c027', '_extract_theta-d957450d500420728bd8ceb576121c1b', '_extract_theta-6aabcd55811e01bfed1652db5bf70eca', '_extract_zi-0e388f950aa4c90d7335f7f76ae148f5', '_smart_matrix-a0bb13ebc44bab0ed4c490409d7a80b0', '_extract_mu-95f34fc933b657158559cdd8290ec781', '_extract_mu-fb4e5bc8ea998534b498253e4b269c82', '_extract_zi-192f3ebab52d3dc6a016b38d4d73d6b5', '_extract_mu-1fe3079cf5b81faf46c59074b9a591e9', '_extract_theta-771b7d830cc7caaf6cff9bcd4f93c906', '_extract_zi-3190c3b3364d1f71d0ec253b7f263ae6', '_extract_theta-7b1b3e5472508d1bc4d0bb8e095d147e', '_smart_matrix-28434d51ffbc0239bc9a744196b4fa1c', '_label_tensorzinb_regressors-b90fcc146f4f357b74080d8fc326fe83', '_smart_matrix-eb4dd98539179fe7e1c6ffbbe2231a5c', '_extract_theta-747d777380a67c1ec3182ffd83db5969', '_extract_theta-38f61e0518a6e32d16e7de722da1c191', '_extract_zi-513c22fac941628cfad7ff54fa04afce', '_extract_zi-f7609eec1c88f67b2a68f33474aaa6d3', '_extract_mu-58ca9b6b5aa5b6c33f20b72e00d5619e', '_extract_mu-eb712beaa5211ea3e117a13999e12a4d', '_extract_theta-3d5c8ae9efaa4050ba5adea4c11ca4b3', '_extract_theta-ff5204461a9cdf7f230cb8aca889e4c9', '_extract_theta-e5d85e59212e67add89fbfc805fd9637', '_label_tensorzinb_regressors-8c470315a96c6d4f7a44372c92c16876', '_extract_mu-6346378912e281883149b1df84e26911', '_extract_theta-336b7f2b56bffaefb277c551317c2737', '_label_tensorzinb_regressors-c8d87bfde0c6d838db3ef4f8a9328003', '_extract_theta-a6077f2f97666cb84d54525685264461', '_label_tensorzinb_regressors-1f71f12835e1960d90861c39a7303c51', '_extract_theta-c4de76a5c0d7d5e7d763e063ae6b7f50', '_smart_matrix-e6515fed2426d37809f01f689378ac52', '_extract_mu-a95bf5bc176d21f5a314a913c52fa63c', '_extract_zi-12c1a25f86f19802f96c66a44f70640b', '_extract_zi-2c50e38285a56f89f95e83febfee04ab', '_smart_matrix-ae60d2317210ba979bccd840e3bed987', '_extract_mu-dd2c0720ee03b2b698ab9e2043c16399', '_smart_matrix-c6225fdbb93831638d74c6b32bbc7034', '_label_tensorzinb_regressors-400f65fb17ef8c1ce0c63433c7ebcb11', '_extract_theta-cc93a4298f1867630831d4012fb70a33', '_extract_mu-0929f9fab7ff5e40fa6e2931d7d91cc3', '_label_tensorzinb_regressors-ca5728d2770785071183f9e8e80d4861', '_extract_mu-44d9fc8d765280002a253364d9f1ada5', '_extract_theta-0e93817ec104f83df8d62cafb8a0b80e', '_smart_matrix-e04885ebb0041d5798b681f66ff2c64b', '_extract_theta-a1d88f4403384abadf08247da0361b7d', '_extract_theta-5a2a190481e96751cb6e38f70d048d8a', '_extract_theta-60214a2104af65f6d9a25bb5572c181d', '_label_tensorzinb_regressors-029e8bc8761965a9217e5f65f6e68746', '_label_tensorzinb_regressors-5cb104460c88ec54ca8c531522f677e2', '_extract_zi-665eb88e319bc656376913b7aeb78225', '_smart_matrix-e8676f300b731434cad40a19c4af4555', '_smart_matrix-c8e22b0b957f3cc63ee910dd80206939', '_smart_matrix-dbcca55059b73c33ac8fd84936802af5', '_extract_theta-62e4f3fe9dad19bc8a3ee1909791061d', '_label_tensorzinb_regressors-356ea51df18e301ffdc9809760a92751', '_label_tensorzinb_regressors-43e66632033ccf694be5257c8b1cd3ac', '_extract_mu-676c8c4c3a1449e60f88b5a7c891211a', '_extract_theta-a8ae9c17a0c6272c8bde18740ec1975e', '_label_tensorzinb_regressors-0b29d140b66792c47c6f052f7eeab4d1', '_smart_matrix-31d08f049e6a92e10209ac82a9a9c7ce', '_smart_matrix-3b46a65322f21915fbbadc53f4a19f5a', '_extract_mu-1f5b1549ed365737914f97dd9a576c2f', '_extract_zi-96e8d6d9027df9a2ea244500458b0e39', '_extract_zi-888db8540ed8e4c9a584e2a87f1d1c08', '_extract_zi-d10d1ca521f34ab897f166f3a18bf129', '_extract_mu-e4f2897bca377c7ea3f89da527e3ba8f', '_label_tensorzinb_regressors-99f1e5aa6298f13bd0d5f3455d5e3f43', '_extract_mu-bf00646465f14d04fa65ba985ca58507', '_label_tensorzinb_regressors-f9b78296ca97cba87f14f4ee0ab96596', '_label_tensorzinb_regressors-4f866a8ad1c34e776c59e50f16744cec', '_extract_zi-e9b374b4ae31fe68550155aa0a7511bd', '_extract_theta-aa8b6a976c8c67e9dfb9286087bf9b38', '_extract_mu-64d856c44cceab1e82282ff6f3464898', '_extract_mu-8f51b0f1f9b17256cb031daca1808479', '_smart_matrix-0fb84002b2a7d13af4bed68b7e5e9890', '_label_tensorzinb_regressors-b88233dbec3270131287be1763b65633', '_extract_mu-785b634695351836caee71b148c81529', '_extract_zi-7ea99503278fe3051908e2d58c96322b', '_extract_zi-89b3a189a63c4b33fca6cd013dea4078', '_extract_mu-b1d7b881b09236112f14a5069c56f333', '_extract_mu-969adc975188520e2af65e08e3765e3e', '_extract_mu-50eefc670244a7a3dbbc0ef46f722575', '_extract_zi-9a29d85f66ae5b9be1fa72ab2188070b', '_extract_mu-93fb9a0754b98b0055e8299d8831280f', '_smart_matrix-06a4f82d07ec514b94307fb648462e81', '_extract_mu-2249a86eaaa0f1e6c211f4769309ac41', '_label_tensorzinb_regressors-94ea0c2a576a5670143747a7f2c45889', '_extract_zi-517701b31fdd8bf2d15db7a198679bff', '_label_tensorzinb_regressors-36d91327262d52de71be5777429c1b24', '_extract_zi-7eed896765f6bfcb6763e472681178cb', '_smart_matrix-28bd2cabef6fa1dac139820f79ee0914', '_extract_mu-8036aaeba5bbfe471d8a335c6dee4ce0', '_label_tensorzinb_regressors-9e73d697ad44da5895259bc7671f8336', '_smart_matrix-31705ef2d96f6d7b2f7beddb79db5d0c', '_extract_theta-e7114adb351d0098496d4402a6b7d53a', '_smart_matrix-19179a9d0c553beec39ec7299e454e6a', '_extract_mu-23576767a05ba48dc5de2095bf0b437d', '_smart_matrix-48ae30ca0b39de2e9214b0cb996d0f4f', '_label_tensorzinb_regressors-e97265212b94fd1d2511a16ec823985a', '_extract_mu-266b56e968a111768165a38c7f29aed6', '_smart_matrix-44c781dfc1fd26ca371abd9553d2b84c', '_smart_matrix-3ca0c3f9e87073e1b8501d6587241e4b', '_smart_matrix-f885e1fd2e2be630f8d56fe9290a8a37', '_smart_matrix-85f05ae49d7eb42e9487bb7f50ce00be', '_extract_theta-98f49c70b0383f9d8220e6f720df6ea3', '_extract_theta-5caec9455ab7f01059cf7e8d94a943d3', '_extract_zi-4591582b05d2401e17099f8608ed1416', '_extract_theta-18486306f957ae3091525e8008ace42d', '_label_tensorzinb_regressors-665b15505d922bece0b7d9408ef11323', '_smart_matrix-197db69285ad65c96b021451529f7bb0', '_label_tensorzinb_regressors-08850e6c9ba509a4bffec4031fda3d5d', '_label_tensorzinb_regressors-53b552d26bd7e6c2cedbf835b68df48e', '_extract_zi-cb73729b34a65618688a3fe6d0c5c197', '_extract_zi-501887d90171060c276401adda1e50db', '_extract_zi-1776c020537996dcb932b66552853ae6', '_extract_theta-0e03cc03451016c2cbfde96f5b2d5419', '_label_tensorzinb_regressors-8b4cdbdb596c78752a71fa6a7403f727', '_extract_zi-f4b575c8300a2039fccad84a5ad95fc5', '_extract_mu-a66edfa42b682f4e23a4d752473a6b13', '_extract_zi-0b68000cbf3f3a6ff6a3a87794c899d9', '_extract_zi-4703561db27c507738cd2a5ae4068a93', '_extract_zi-db0bc24d19d57630e9c3e6744b807f7f', '_extract_zi-6caea0b4c067261ec2d0628ff8b2dc94', '_extract_theta-881db04e91aa56e93decfc5e4809274a', '_label_tensorzinb_regressors-bd60799b97edd7bd1c264af2b3e5a5a3', '_extract_mu-3b803d8fd18dff2b828dbff1b190119a', '_label_tensorzinb_regressors-ec6bc1c7b6ef21999568b1a54947cf60', '_extract_mu-d78d9ccd2fcc33d731dc6ccede93622f', '_extract_zi-95e6f525e620ff79c4fe2985182d0c17', '_extract_theta-3a2c9e7ba2bfd8e4da1e2f7744f200b2', '_extract_theta-f96828d9aa23ea494ffb79552c1c42d7', '_label_tensorzinb_regressors-c8d40308d6adf1d089e99e24efa59a62', '_extract_mu-95cdbdd313f672698bed9ed2c4ad5877', '_extract_zi-e6038a2de9319aa5cf839ac61abeb243', '_extract_theta-f1a3726e53d8107e973b38bd216e6925', '_extract_mu-ea51531fde3ec6cf44f23aed24ba672f', '_smart_matrix-419abaab45a806dade7936c7e7155f29', '_extract_mu-1cfb883e31db2567bbda281c3d495308', '_smart_matrix-db1c8c86a1c9dd20fcc9cfc171d597bf', '_label_tensorzinb_regressors-7f47525d2068de65a6d65273995867ce', '_label_tensorzinb_regressors-d91e2bef1abf62f486353ec6b666f518', '_smart_matrix-a42202799e1bc56777552b6c7e15a93a', '_label_tensorzinb_regressors-9b95546d69f3111d5530a4de0521cf2b', '_smart_matrix-2f74303100c8ba6c01c1873f1e907699', '_extract_theta-6a0fedcf297518bd760d6aba535ae824', '_extract_theta-1d75fa261fd7b846fa2878577ee28c96', '_extract_mu-48623f47ca4369ed1a3ced18570adb70', '_smart_matrix-7015fb01ddb4c48fb114865a11a21454', '_label_tensorzinb_regressors-e177a5a52955e0b8ccee8222683ce788', '_extract_zi-0269b6941a0ad80a1adfc8daeceb6d81', '_extract_mu-25a825ccd3e073b3941d32c69d912fff', '_smart_matrix-f14754c74dd2a019e15d5b2933f87b3b', '_extract_zi-7fc511f96bcb8cd0740ebe9d5cdcc3f8', '_label_tensorzinb_regressors-52d279829fd6d59c6fb1371458027c42', '_extract_mu-c977acb3d1544e5248e3e1b550f4fee6', '_extract_mu-2cd74ea3e2469c627f0709492d05fbe3', '_extract_zi-3aed343552753ce5648f99a004908c8d', '_extract_mu-95156a310363f71bf0c4c92ef8d635fb', '_extract_zi-2b4b085b3ae90d4d5c292a6e4841e042', '_extract_zi-d83dacf8fb15592fe0473045aab9116e', '_label_tensorzinb_regressors-73564de56ca095b592003b2606f17b97', '_label_tensorzinb_regressors-fd44ceaa99a777ba35e95838f51a17eb', '_extract_theta-ed4ddf8dca4337152a96710461f52bd9', '_smart_matrix-4ac18bafe57cc64fb807a88d9a3f5184', '_extract_zi-bb30239befdb3b242b2340e675654f13', '_extract_theta-3366d344756ff9ea34357a809331fa61', '_label_tensorzinb_regressors-bcb1869e4c31e8444c0f2c1fa6178592', '_extract_mu-739d19384a134e5b7b5daa0838846f58', '_smart_matrix-740e0b206501f8d3a808e2e04f04d06b', '_smart_matrix-b6e33413cbe5e80b0ae00d41020572a9', '_extract_theta-fa12583d5ae510cbd743a292a5b9f575', '_label_tensorzinb_regressors-e4e20c66eda18bd4c7838cb0ac5e876f', '_label_tensorzinb_regressors-e1ba4f4286c62befb347269e546e026d', '_extract_mu-ec31286147ab84e1f710652990bd2111', '_extract_theta-e6b6fadcbde387d1559ee6da9017c7fb', '_label_tensorzinb_regressors-8592a3da3e10ac7c8b57a6ac5c01fb43', '_extract_zi-29823a48fc758ffa2b1c7d0e4679619f', '_extract_mu-525bf285dc714796e4b075a9fbc42e18', '_extract_zi-adb68d080965cf4853e1793013796a04', '_extract_mu-b4a8035a25833d455f950f5676a03edd', '_smart_matrix-960cdc7ebf8217fb3e897dc81c00fd20', '_extract_mu-3d918ae318ec8e0a1ea4fe4bebe818e1', '_extract_theta-c0bee785d6db51a1ea0b31b68756533a', '_extract_zi-28c45a6b9a450b8dd678e0cc050e7456', '_extract_mu-eb22222c12e58f37f799b1858d7c2916', '_extract_mu-b42cf0e0f84ddf7ef106db15d31dae85', '_extract_mu-8d0c9a1cbcb50e977dd65dc5e1e1de63', '_smart_matrix-519884062f8da53b01c93fefb3fc94ba', '_extract_theta-8e6aa42890518cc35206739724964511', '_extract_zi-77e44179c53f3d41ca7e60803f7df08b', '_extract_mu-4cc1322e7acde9e43083448f1a05ab84', '_extract_zi-cfa79b722a0b7f3dcf03cd09c7428a7a', '_label_tensorzinb_regressors-a02261e8484b967da1775bfba13bf9de', '_smart_matrix-8d1fecd4c0c35bc38967c94af7f575a5', '_extract_zi-74a77aba29899fedfb7a5921867f3c3e', '_extract_theta-105e55e2ad60f66d8c5848c7efadfcbc', '_label_tensorzinb_regressors-40e793d701058f505572dfee1f668255', '_label_tensorzinb_regressors-75d073907aaca300ce95ab5f5f72da67', '_extract_zi-fa8bb94b5bbf23d16d7de7c207f3cc47', '_extract_mu-22d3790884536e417a6a45b7b81db4ea', '_smart_matrix-1eef17819fa69ca380cfe07d83dc1425', '_extract_mu-de932e2af82943f5bd12006628985fa3', '_extract_theta-5065da0e59916c786abcca66c47c20e7', '_label_tensorzinb_regressors-54681e0f4d308df310822bcf884ddf13', '_smart_matrix-f0f1e4f5d298e7c50f3ff8d3e658aca7', '_extract_theta-646f7f98fdcbc3519eddc29b16da97e2', '_extract_mu-62796fd0fe8dcc5e1ea816f452cea9fd', '_extract_zi-b014177a9eaf15032240a6b426c12c04', '_extract_mu-8476dd3e8f5cc86ac73ee2e830bf36c8', '_extract_theta-057267004726c73cf7abe724cf7b302e', '_extract_zi-9b2a9f24d6bb453e8dcd6863baf59336', '_extract_theta-0b834e4d68c099ad2cac2b6a168cb7f4', '_extract_theta-f1b5ea9203505e6136ecbd4d5a69b9a6', '_extract_mu-b1a90ece30118978d541b4bd617c544c', '_extract_zi-383ae3f8f56ecc9f04c10937dbd0962c', '_extract_mu-838b3b53914d623b0bfb949447051f90', '_smart_matrix-a5c216ee0444736d34c56bc43852375b', '_extract_theta-6b2f921f668c6625627e2310fb00804b', '_extract_zi-7bfb804fb7bb7dcd072171bdfe147b99', '_label_tensorzinb_regressors-099e0deb62c4efefac76cbc25e3cc3bb', '_label_tensorzinb_regressors-df3d4644b542bf01a787ba753863bfcc', '_smart_matrix-a12133f630cb63369d428d6b35937b88', '_extract_mu-19cf940a1e2fc20b8b711cc555c2eff8', '_extract_zi-83607cc1c67f60cc2f1341ad145ee82d', '_extract_theta-929d5f350c4e1d615ed6b7683b03bad3', '_extract_mu-036b932b6917760f5ff781dd56113787', '_smart_matrix-053e976ed9a3a2eb2e1aa41fadb85b4e', '_label_tensorzinb_regressors-43d0e09e4f710e16ff49252cd70cf6c9', '_extract_mu-767ee9e74cbc9e225078feff2121208c', '_smart_matrix-7e023dd81837e306f8fc046e177d039c', '_smart_matrix-6b2dd4ea9b672f8946b1c98fa686a4d2', '_label_tensorzinb_regressors-fcf0ea70f588093304f7cb1e4ab66a21', '_extract_zi-88248fde2866eadcaa08642f2a752753', '_label_tensorzinb_regressors-7a6033ba91f38c180fa7ab57b89645d5', '_extract_mu-6e55e94de9a497ef0a2b2743cbbb21e0', '_smart_matrix-3981275eda6a01841261e88e1cd881c0', '_label_tensorzinb_regressors-ff36abe674e5036d6f1fcc174d39764e', '_extract_theta-c

2025-09-12 20:04:14,094 - distributed.nanny - WARNING - Worker process still alive after 4.0 seconds, killing
2025-09-12 20:04:14,095 - distributed.nanny - WARNING - Worker process still alive after 4.0 seconds, killing
2025-09-12 20:04:14,096 - distributed.nanny - WARNING - Worker process still alive after 4.0 seconds, killing
2025-09-12 20:04:14,110 - distributed.nanny - WARNING - Worker process still alive after 4.0 seconds, killing