Thie notebook creates simulations to contextualize the FN and FP rate for the hypothesis "cre of interest is significantly different from minP".
- negative simulations (cre_oi=minP) for quantifying the FP rate.
- positive simulations (cre_oi!=minP) for quantifying FN rate.

# Setup

In [1]:
import scMPRAforge as scm
from dask_jobqueue import SLURMCluster
from dask.distributed import Client, LocalCluster

%load_ext autoreload
%autoreload 2

2026-01-14 16:04:39.675342: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-01-14 16:04:39.678646: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /apps/software/2024a/software/code-server/4.103.0/lib:/apps/software/2024a/software/gettext/0.22.5-GCCcore-13.3.0/lib:/apps/software/2024a/software/libiconv/1.17-GCCcore-13.3.0/lib:/apps/software/2024a/software/ncurses/6.5-GCCcore-13.3.0/lib:/apps/software/2024a/software/libxml2/2.12.7-GCCcore-13.3.0/lib:/apps/software/2024a/software/XZ/5.4.5-GCCcore-13.3.0/lib:/apps/software/2024a/software/expat/2.6.2-GCCcore-13.3.0/lib:/apps/software/2024a/software/cURL/8.7.1-GCCcore-13.3.0/lib:/apps/software/2024a/software/OpenSSL/3/lib64:/apps/software/2024a/software/zlib/1.3.1-GCCcore-13.3.0/lib:/apps/software/2024a/software/GCCcore/13.3.0/lib64
2026-01-14 16:04:39.678659: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

In [2]:
local=True
if local:
    cluster=LocalCluster(memory_limit='48G')
    client=Client(cluster)
else:
    cluster=SLURMCluster(
        cores=2,#cores per slurm job
        memory="32G",#memory per slurm job
        processes=1,#dask workers per slurm jobTrueT
        job_extra_directives=["-p day", 
            f"--job-name=simclust_worker",
            f"--time=4:00:00",
            f"--output=worker_%j.out"]
    )
    cluster.scale(jobs=4)
    client = Client(cluster,
            timeout=f"{5*60}s",   # Client <-> scheduler timeout 
            heartbeat_interval="20s"  # Worker heartbeat interval
        )

In [4]:
data_root="/nfs/roberts/project/pi_skr2/shared/tabula_data"

# Creating artificial libraries

In [ ]:
#making up the CREs
spread_gt,spread_hypothesis=scm.activity_spread(
    cell_types=list(scm.SHENDURE_BOUNDS.cells_per_cell_type.keys()),
    minimum=scm.SHENDURE_BOUNDS.min_mpra_umi,
    maximum=scm.SHENDURE_BOUNDS.max_mpra_umi,
    minp_value=scm.SHENDURE_BOUNDS.reference_activity,
    total=100,
    frac_active=0.5,
    ct_specificity=.2)

libraries=[scm.simulate_library(CREs=spread_gt["cre_id"],
                 library_model=scm.SHENDURE_BOUNDS.library_model)
                 for i in range(5)]

In [ ]:
spread_hypothesis.to_tsv(f"{data_root}/pow_sim_2026-01-03_hypo.tsv")

# Creating sim

In [ ]:
sim=scm.de_novo_simulation(location=data_root,
                            name="pow_sim_2026-01-03",
                            client=client,
                            libraries=libraries,
                            library_mapping="corresponding",
                            n_sims=5,
                            experiment_bounds=scm.SHENDURE_BOUNDS,
                            ground_truth=spread_gt)

In [ ]:
sim.gamut()

In [ ]:
sim.save()

# Fit orthos

In [ ]:
#loading back into mem, assuming notebook shut down after last task
sim=scm.de_novo_simulation(location=data_root,
                            name="pow_sim_2026-01-03",
                            client=client)

In [ ]:
sim.fit_orthos()

In [ ]:
sim.save()

# Wald precompute: sandwich

In [ ]:
#loading back into mem, assuming notebook shut down after last task
sim=scm.de_novo_simulation(location=data_root,
                            name="pow_sim_2026-01-03",
                            client=client)

In [ ]:
sim.precompute_wald(cov_method="sandwich")

In [ ]:
sim.save()

# Wald precompute: opg

In [ ]:
#loading back into mem, assuming notebook shut down after last task
sim=scm.de_novo_simulation(location=data_root,
                            name="pow_sim_2026-01-03",
                            client=client)

In [ ]:
sim.precompute_wald(cov_method="opg")

In [ ]:
sim.save()

# Hypothesis testing

In [ ]:
#loading back into mem, assuming notebook shut down after last task
sim=scm.de_novo_simulation(location=data_root,
                            name="pow_sim_2026-01-03",
                            client=client)

Add a basic hypothesis set

In [ ]:
spread_hypothesis=scm.HypothesisSet.from_tsv(f"{data_root}/pow_sim_2026-01-03_hypo.tsv")

In [ ]:
sim.add_hypothesis_set(name="spread",hypotheses=spread_hypothesis)

Run mwu

In [ ]:
sim.mwu("spread")

In [ ]:
sim.save()

In [ ]:
sim.wald("spread")

In [ ]:
sim.wald("spread",cov_method="opg")

In [ ]:
sim.save()

# Summary

In [5]:
#loading back into mem, assuming notebook shut down after last task
sim=scm.de_novo_simulation(location=data_root,
                            name="pow_sim_2026-01-03",
                            client=client)

scMPRAforge: INFO: 'state.parquet' found for 'pow_sim_2026-01-03', loading.

In [6]:
sim.list_tests()

{'spread': ['mwu', 'wald_opg', 'wald_sandwich']}

In [10]:
sim._classifier_summary(hypothesis_set_name="spread",test_type="mwu")

     comparison_CRE reference_CRE     comparison_cell_type  \
0        inactive_0     reference           Cardiomyocytes
1        inactive_0     reference  EpiblastPrimitiveStreak
2        inactive_0     reference       ExEndodermParietal
3        inactive_0     reference       ExEndodermVisceral
4        inactive_0     reference       Haematoendothelial
...             ...           ...                      ...
5495      active_45     active_45                reference
5496      active_46     active_46                reference
5497      active_47     active_47                reference
5498      active_48     active_48                reference
5499      active_49     active_49                reference

          reference_cell_type  meta  test_statistic       p_value  \
0              Cardiomyocytes     0        143989.0  6.477094e-01
1     EpiblastPrimitiveStreak     0       3068977.5  6.391818e-01
2          ExEndodermParietal     0       6038647.0  1.661610e-02
3          ExEndodermVisceral     0       2902892.5  3.929909e-01
4          Haematoendothelial     0        322462.5  8.245754e-01
...                       ...   ...             ...           ...
5495          SurfaceEctoderm     0      38833808.5  6.749567e-01
5496          SurfaceEctoderm     0      30701340.5  2.723733e-01
5497          SurfaceEctoderm     0      21858158.0  7.250828e-44
5498          SurfaceEctoderm     0      12639686.0  1.576764e-01
5499          SurfaceEctoderm     0      19191631.0  7.030319e-01

      fold_change  flattened              ref_mean             comp_mean  \
0        1.122470       True  0.012772305202551903  0.015561231975419032
1        0.949530       True  0.015259316922416666  0.013984484013818133
2        1.228339       True  0.010886331819568218  0.015655493427906952
3        1.118367       True   0.01155729843120934  0.014108971780954382
4        1.028264       True  0.011435634447625631  0.012041496576213007
...           ...        ...                   ...                   ...
5495     1.000359       True     65.30445780621022     65.32790420122166
5496     1.029332       True     6.402449682345704     6.590537346732208
5497     0.601216       True     54.39607939584091     32.69979082869138
5498     0.936356       True     60.19731713091773     56.36546564712449
5499     1.006342       True     48.07630646264291    48.381252121929414

     test_type          bh_p  comparison_truth  reference_truth  \
0          mwu  9.504807e-01          0.019311         0.019311
1          mwu  9.466363e-01          0.019311         0.019311
2          mwu  1.281747e-01          0.019311         0.019311
3          mwu  8.563590e-01          0.019311         0.019311
4          mwu  9.791021e-01          0.019311         0.019311
...        ...           ...               ...              ...
5495       mwu  9.543213e-01        346.477666       346.477666
5496       mwu  7.810531e-01         22.699749        22.699749
5497       mwu  7.290595e-43        161.621961       270.766683
5498       mwu  6.436762e-01        321.033991       321.033991
5499       mwu  9.597660e-01        244.263523       244.263523

      gt_effect_size  gt_null  reject_null
0           1.000000     True        False
1           1.000000     True        False
2           1.000000     True        False
3           1.000000     True        False
4           1.000000     True        False
...              ...      ...          ...
5495        1.000000     True        False
5496        1.000000     True        False
5497        0.596905    False         True
5498        1.000000     True        False
5499        1.000000     True        False

[5500 rows x 18 columns]
     comparison_CRE reference_CRE     comparison_cell_type  \
0        inactive_0     reference           Cardiomyocytes
1        inactive_0     reference  EpiblastPrimitiveStreak
2        inactive_0     reference       ExEndodermParietal
3        inactive_0     reference       ExEndodermVisceral
4        inactive_0     reference       Haematoendothelial
...             ...           ...                      ...
5495      active_45     active_45                reference
5496      active_46     active_46                reference
5497      active_47     active_47                reference
5498      active_48     active_48                reference
5499      active_49     active_49                reference

          reference_cell_type  meta  test_statistic       p_value  \
0              Cardiomyocytes     0        335580.0  2.605412e-01
1     EpiblastPrimitiveStreak     0       8615388.0  9.918651e-01
2          ExEndodermParietal     0      14809514.0  2.224731e-01
3          ExEndodermVisceral     0       7231086.5  5.804069e-01
4          Haematoendothelial     0        821380.5  5.908461e-01
...                       ...   ...             ...           ...
5495          SurfaceEctoderm     0      25197099.0  5.071173e-01
5496          SurfaceEctoderm     0       1900112.0  1.520797e-01
5497          SurfaceEctoderm     0      30453871.0  3.760491e-40
5498          SurfaceEctoderm     0      48267638.0  7.371261e-01
5499          SurfaceEctoderm     0      13717376.0  3.429006e-01

      fold_change  flattened              ref_mean             comp_mean  \
0        0.767971       True  0.018014281068914118  0.011514160320698519
1        1.000714       True  0.014580761719077406  0.014598304507023263
2        1.114650       True  0.012198099793633732  0.014743120387067377
3        0.942294       True  0.014296364564731379   0.01289431276115427
4        1.143971       True  0.012022509754104904  0.015193118187130317
...           ...        ...                   ...                   ...
5495     0.983282       True     63.21432435977427     62.15733689738263
5496     0.924676       True     7.289410581491698     6.739591500733903
5497     0.647487       True    50.947726062350455     32.98444437146919
5498     1.011503       True     60.50436872282637      61.2004516443309
5499     1.035495       True    46.372004558041866     48.01834973872593

     test_type          bh_p  comparison_truth  reference_truth  \
0          mwu  7.348598e-01          0.019311         0.019311
1          mwu  9.980376e-01          0.019311         0.019311
2          mwu  6.924741e-01          0.019311         0.019311
3          mwu  9.132210e-01          0.019311         0.019311
4          mwu  9.161093e-01          0.019311         0.019311
...        ...           ...               ...              ...
5495       mwu  8.956792e-01        346.477666       346.477666
5496       mwu  5.848877e-01         22.699749        22.699749
5497       mwu  3.851527e-39        161.621961       270.766683
5498       mwu  9.563163e-01        321.033991       321.033991
5499       mwu  8.005976e-01        244.263523       244.263523

      gt_effect_size  gt_null  reject_null
0           1.000000     True        False
1           1.000000     True        False
2           1.000000     True        False
3           1.000000     True        False
4           1.000000     True        False
...              ...      ...          ...
5495        1.000000     True        False
5496        1.000000     True        False
5497        0.596905    False         True
5498        1.000000     True        False
5499        1.000000     True        False

[5500 rows x 18 columns]
     comparison_CRE reference_CRE     comparison_cell_type  \
0        inactive_0     reference           Cardiomyocytes
1        inactive_0     reference  EpiblastPrimitiveStreak
2        inactive_0     reference       ExEndodermParietal
3        inactive_0     reference       ExEndodermVisceral
4        inactive_0     reference       Haematoendothelial
...             ...           ...                      ...
5495      active_45     active_45                reference
5496      active_46     active_46                reference
5497      active_47     active_47                reference
5498      active_48     active_48                reference
5499      active_49     active_49                reference

          reference_cell_type  meta  test_statistic       p_value  \
0              Cardiomyocytes     0        260333.5  7.669963e-01
1     EpiblastPrimitiveStreak     0       7016877.5  8.015670e-01
2          ExEndodermParietal     0      12842013.5  7.324267e-01
3          ExEndodermVisceral     0       6458220.5  7.268541e-01
4          Haematoendothelial     0        687652.5  7.262751e-01
...                       ...   ...             ...           ...
5495          SurfaceEctoderm     0      42621656.5  5.173749e-01
5496          SurfaceEctoderm     0      15918792.0  2.268679e-01
5497          SurfaceEctoderm     0      11858461.0  6.032012e-20
5498          SurfaceEctoderm     0      53912538.5  9.228222e-01
5499          SurfaceEctoderm     0      10726689.5  7.526049e-01

      fold_change  flattened              ref_mean             comp_mean  \
0        0.951189       True  0.011996500427626788  0.010922830354970658
1        1.028096       True  0.011390314219025255  0.011991304854147122
2        1.038477       True  0.012461044618309769   0.01332528673130895
3        0.977624       True   0.01396670560799329   0.01343042541182582
4        0.958899       True   0.01506604853949911  0.014035802667325514
...           ...        ...                   ...                   ...
5495     1.020325       True      64.5607043056358     65.87313415950435
5496     0.958212       True     6.611388783538648     6.334690981369158
5497     0.678897       True     48.07877971947464     32.63732904973579
5498     1.000288       True    61.449270051860466     61.46699101891755
5499     0.979946       True     48.66142111499575     47.68538177677998

     test_type          bh_p  comparison_truth  reference_truth  \
0          mwu  9.524008e-01          0.019311         0.019311
1          mwu  9.598559e-01          0.019311         0.019311
2          mwu  9.413147e-01          0.019311         0.019311
3          mwu  9.403546e-01          0.019311         0.019311
4          mwu  9.403546e-01          0.019311         0.019311
...        ...           ...               ...              ...
5495       mwu  9.024934e-01        346.477666       346.477666
5496       mwu  6.955506e-01         22.699749        22.699749
5497       mwu  5.632609e-19        161.621961       270.766683
5498       mwu  9.891877e-01        321.033991       321.033991
5499       mwu  9.504199e-01        244.263523       244.263523

      gt_effect_size  gt_null  reject_null
0           1.000000     True        False
1           1.000000     True        False
2           1.000000     True        False
3           1.000000     True        False
4           1.000000     True        False
...              ...      ...          ...
5495        1.000000     True        False
5496        1.000000     True        False
5497        0.596905    False         True
5498        1.000000     True        False
5499        1.000000     True        False

[5500 rows x 18 columns]
     comparison_CRE reference_CRE     comparison_cell_type  \
0        inactive_0     reference           Cardiomyocytes
1        inactive_0     reference  EpiblastPrimitiveStreak
2        inactive_0     reference       ExEndodermParietal
3        inactive_0     reference       ExEndodermVisceral
4        inactive_0     reference       Haematoendothelial
...             ...           ...                      ...
5495      active_45     active_45                reference
5496      active_46     active_46                reference
5497      active_47     active_47                reference
5498      active_48     active_48                reference
5499      active_49     active_49                reference

          reference_cell_type  meta  test_statistic       p_value  \
0              Cardiomyocytes     0        237928.5  9.370098e-01
1     EpiblastPrimitiveStreak     0       5913268.5  2.361693e-01
2          ExEndodermParietal     0      11011479.5  9.849269e-01
3          ExEndodermVisceral     0       5142542.5  3.569760e-01
4          Haematoendothelial     0        563720.0  6.604036e-01
...                       ...   ...             ...           ...
5495          SurfaceEctoderm     0      65221694.5  4.859116e-01
5496          SurfaceEctoderm     0       2442211.0  2.304696e-01
5497          SurfaceEctoderm     0      51668119.5  1.101337e-62
5498          SurfaceEctoderm     0       3764546.5  5.547150e-01
5499          SurfaceEctoderm     0      24181496.5  5.619770e-01

      fold_change  flattened              ref_mean             comp_mean  \
0        1.055534       True  0.010130288872850945  0.011248209018543731
1        1.139712       True   0.01204960217513662   0.01513019504147417
2        0.988204       True  0.015287506751796798   0.01498921325091529
3        0.916640       True  0.013848871810427932  0.011860818726032951
4        1.055679       True  0.013250745817716458  0.014545334937523746
...           ...        ...                   ...                   ...
5495     1.017580       True     63.05132319928583     64.15995174846803
5496     1.068873       True     6.109437818358988     6.530903137524066
5497     0.618972       True     52.27801697172854    32.354794902006404
5498     1.051640       True     59.80032837483827      62.8889267597369
5499     1.014507       True     46.41404477672905     47.08752599350974

     test_type          bh_p  comparison_truth  reference_truth  \
0          mwu  9.929661e-01          0.019311         0.019311
1          mwu  6.716294e-01          0.019311         0.019311
2          mwu  9.964801e-01          0.019311         0.019311
3          mwu  7.873865e-01          0.019311         0.019311
4          mwu  9.373165e-01          0.019311         0.019311
...        ...           ...               ...              ...
5495       mwu  8.615713e-01        346.477666       346.477666
5496       mwu  6.659924e-01         22.699749        22.699749
5497       mwu  1.134336e-61        161.621961       270.766683
5498       mwu  8.954894e-01        321.033991       321.033991
5499       mwu  9.000797e-01        244.263523       244.263523

      gt_effect_size  gt_null  reject_null
0           1.000000     True        False
1           1.000000     True        False
2           1.000000     True        False
3           1.000000     True        False
4           1.000000     True        False
...              ...      ...          ...
5495        1.000000     True        False
5496        1.000000     True        False
5497        0.596905    False         True
5498        1.000000     True        False
5499        1.000000     True        False

[5500 rows x 18 columns]
     comparison_CRE reference_CRE     comparison_cell_type  \
0        inactive_0     reference           Cardiomyocytes
1        inactive_0     reference  EpiblastPrimitiveStreak
2        inactive_0     reference       ExEndodermParietal
3        inactive_0     reference       ExEndodermVisceral
4        inactive_0     reference       Haematoendothelial
...             ...           ...                      ...
5495      active_45     active_45                reference
5496      active_46     active_46                reference
5497      active_47     active_47                reference
5498      active_48     active_48                reference
5499      active_49     active_49                reference

          reference_cell_type  meta  test_statistic       p_value  \
0              Cardiomyocytes     0        403767.0  5.319992e-01
1     EpiblastPrimitiveStreak     0       9960393.5  8.866685e-01
2          ExEndodermParietal     0      18195716.5  4.743679e-01
3          ExEndodermVisceral     0       9261124.0  8.834376e-01
4          Haematoendothelial     0        991704.0  2.749791e-01
...                       ...   ...             ...           ...
5495          SurfaceEctoderm     0      89944831.0  8.270655e-02
5496          SurfaceEctoderm     0      53302370.5  6.734556e-01
5497          SurfaceEctoderm     0      18867601.5  6.672008e-29
5498          SurfaceEctoderm     0       8530709.0  9.818969e-01
5499          SurfaceEctoderm     0       8632328.0  3.880290e-01

      fold_change  flattened              ref_mean             comp_mean  \
0        1.080063       True   0.00903368244075109  0.010557571994472825
1        0.972446       True  0.012282170945273174  0.011668208533637925
2        0.948712       True  0.015008892006219243  0.013726235540371112
3        0.985160       True  0.013199901081460075  0.012855625716414965
4        0.829522       True  0.018491165357853667  0.013634056755329249
...           ...        ...                   ...                   ...
5495     1.048610       True     63.14705471328729      66.2171032567453
5496     0.985588       True     6.429436446077141     6.336628125218815
5497     0.657099       True    52.474422373220754    34.477446845955406
5498     0.999874       True     59.73758263830786    59.730032306323366
5499     0.962071       True      47.5944303623616    45.788832661897715

     test_type          bh_p  comparison_truth  reference_truth  \
0          mwu  8.713507e-01          0.019311         0.019311
1          mwu  9.779971e-01          0.019311         0.019311
2          mwu  8.498448e-01          0.019311         0.019311
3          mwu  9.776472e-01          0.019311         0.019311
4          mwu  7.228229e-01          0.019311         0.019311
...        ...           ...               ...              ...
5495       mwu  4.139090e-01        346.477666       346.477666
5496       mwu  9.286517e-01         22.699749        22.699749
5497       mwu  6.494875e-28        161.621961       270.766683
5498       mwu  9.982061e-01        321.033991       321.033991
5499       mwu  8.053433e-01        244.263523       244.263523

      gt_effect_size  gt_null  reject_null
0           1.000000     True        False
1           1.000000     True        False
2           1.000000     True        False
3           1.000000     True        False
4           1.000000     True        False
...              ...      ...          ...
5495        1.000000     True        False
5496        1.000000     True        False
5497        0.596905    False         True
5498        1.000000     True        False
5499        1.000000     True        False

[5500 rows x 18 columns]

   replicate     auroc     auprc
0          0  0.989646  0.978985
1          1  0.990315  0.980703
2          2  0.984492  0.974943
3          3  0.974656  0.961427
4          4  0.982285  0.967348

In [13]:
sim._all_classifier_summary("spread")

scMPRAforge: INFO: Dropped 7 or 0.1% of tests with NA values for test:wald_opg, rep:0.
scMPRAforge: INFO: Dropped 7 or 0.1% of tests with NA values for test:wald_opg, rep:1.
scMPRAforge: INFO: Dropped 7 or 0.1% of tests with NA values for test:wald_opg, rep:2.
scMPRAforge: INFO: Dropped 7 or 0.1% of tests with NA values for test:wald_opg, rep:3.
scMPRAforge: INFO: Dropped 7 or 0.1% of tests with NA values for test:wald_opg, rep:4.
scMPRAforge: INFO: Dropped 63 or 1.1% of tests with NA values for test:wald_sandwich, rep:0.
scMPRAforge: INFO: Dropped 63 or 1.1% of tests with NA values for test:wald_sandwich, rep:1.
scMPRAforge: INFO: Dropped 63 or 1.1% of tests with NA values for test:wald_sandwich, rep:2.
scMPRAforge: INFO: Dropped 63 or 1.1% of tests with NA values for test:wald_sandwich, rep:3.
scMPRAforge: INFO: Dropped 63 or 1.1% of tests with NA values for test:wald_sandwich, rep:4.

   replicate     auroc     auprc           test
0          0  0.989646  0.978985            mwu
1          1  0.990315  0.980703            mwu
2          2  0.984492  0.974943            mwu
3          3  0.974656  0.961427            mwu
4          4  0.982285  0.967348            mwu
0          0  0.920082  0.858811       wald_opg
1          1  0.920082  0.858811       wald_opg
2          2  0.920082  0.858811       wald_opg
3          3  0.920082  0.858811       wald_opg
4          4  0.920082  0.858811       wald_opg
0          0  0.916257  0.853205  wald_sandwich
1          1  0.916257  0.853205  wald_sandwich
2          2  0.916257  0.853205  wald_sandwich
3          3  0.916257  0.853205  wald_sandwich
4          4  0.916257  0.853205  wald_sandwich

# Shutdown

In [30]:
client.close()
cluster.close()