A better version of `power_shendure_vs_minp.ipynb` with a more representative distribution of positive and negative effects. Specifically, we will be using the real values, plus many negatives.

Based on UKBB paper, expect ~30% of library to be active. So we will add 2x original size of negatives... 

We will also reduce computational burden by producing half-orthos.

# Imports & dask cluster creation

In [1]:
import scMPRAforge as scm
from dask_jobqueue import SLURMCluster
from dask.distributed import Client, LocalCluster
from pathlib import Path

%load_ext autoreload
%autoreload 2

2026-01-23 14:32:44.104545: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-01-23 14:32:44.107563: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /apps/software/2024a/software/code-server/4.103.0/lib:/apps/software/2024a/software/gettext/0.22.5-GCCcore-13.3.0/lib:/apps/software/2024a/software/libiconv/1.17-GCCcore-13.3.0/lib:/apps/software/2024a/software/ncurses/6.5-GCCcore-13.3.0/lib:/apps/software/2024a/software/libxml2/2.12.7-GCCcore-13.3.0/lib:/apps/software/2024a/software/XZ/5.4.5-GCCcore-13.3.0/lib:/apps/software/2024a/software/expat/2.6.2-GCCcore-13.3.0/lib:/apps/software/2024a/software/cURL/8.7.1-GCCcore-13.3.0/lib:/apps/software/2024a/software/OpenSSL/3/lib64:/apps/software/2024a/software/zlib/1.3.1-GCCcore-13.3.0/lib:/apps/software/2024a/software/GCCcore/13.3.0/lib64
2026-01-23 14:32:44.107573: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

In [2]:
local=True
if local:
    cluster=LocalCluster(memory_limit='48G')
    client=Client(cluster)
else:
    cluster=SLURMCluster(
        cores=2,#cores per slurm job
        memory="32G",#memory per slurm job
        processes=1,#dask workers per slurm jobTrueT
        job_extra_directives=["-p day", 
            f"--job-name=simclust_worker",
            f"--time=4:00:00",
            f"--output=worker_%j.out"]
    )
    cluster.scale(jobs=2)
    client = Client(cluster,
            timeout=f"{5*60}s",   # Client <-> scheduler timeout 
            heartbeat_interval="20s"  # Worker heartbeat interval
        )

In [3]:
client.dashboard_link

'http://127.0.0.1:8787/status'

# Ground truth creation

We will use parameter estimates from by_cell_type models as we expect these to be the most accurate.

In [4]:
data_root=Path("/nfs/roberts/project/pi_skr2/shared/tabula_data")

In [5]:
primordial=scm.ortho.load(client,data_root/"shendure","ortho_primordial_v4")

In [6]:
primordial.compute_model_qc()

In [7]:
import pandas as pd

In [8]:
vals=[]
for key in primordial.by_cell_qc.keys():
    key="SurfaceEctoderm"
    working=primordial.by_cell_qc[key]['dat'].reset_index().drop(columns=["mean(umis_mpra_bc)"])
    working["cell_type"]=key
    vals.append(working)
vals=pd.concat(vals)
vals=vals.groupby(["cre_id","cell_type"]).mean().reset_index()
vals

                cre_id        cell_type         mu
0      Bend5_chr4_8168  SurfaceEctoderm   0.019097
1      Bend5_chr4_8174  SurfaceEctoderm    0.01163
2      Bend5_chr4_8175  SurfaceEctoderm   0.671256
3      Bend5_chr4_8179  SurfaceEctoderm   0.019683
4      Bend5_chr4_8199  SurfaceEctoderm   0.004408
..                 ...              ...        ...
134  Txndc12_chr4_7978  SurfaceEctoderm   0.153156
135             eef1aP  SurfaceEctoderm  88.727592
136              pgk1P  SurfaceEctoderm  16.479346
137          reference  SurfaceEctoderm   0.007241
138               ubcP  SurfaceEctoderm  14.532331

[139 rows x 3 columns]

In [24]:
vals.dtypes

cre_id                     object
cell_type                  object
mu           Sparse[float64, 1.0]
dtype: object

In [25]:
vals["mu"] = vals["mu"].astype(float)

In [27]:
vals.dtypes

cre_id        object
cell_type     object
mu           float64
dtype: object

Now that we have reasonable mu estimates for the real CRE, let us add 200% "indistinguishable from minP".

In [9]:
#make "corresponding" inactive CREs...
mapping = {
    val: f"inactive_{i}"
    for i, val in enumerate(vals["cre_id"].unique())
}
mapping

{'Bend5_chr4_8168': 'inactive_0',
 'Bend5_chr4_8174': 'inactive_1',
 'Bend5_chr4_8175': 'inactive_2',
 'Bend5_chr4_8179': 'inactive_3',
 'Bend5_chr4_8199': 'inactive_4',
 'Btg1_chr10_9578': 'inactive_5',
 'Btg1_chr10_9588': 'inactive_6',
 'Btg1_chr10_9593': 'inactive_7',
 'Btg1_chr10_9612': 'inactive_8',
 'Btg1_chr10_9613': 'inactive_9',
 'Cdk5r1_chr11_12559': 'inactive_10',
 'Cdk5r1_chr11_12562': 'inactive_11',
 'Cdk5r1_chr11_12574': 'inactive_12',
 'Cdk5r1_chr11_12575': 'inactive_13',
 'Cdk5r1_chr11_12582': 'inactive_14',
 'Cdk5r1_chr11_12590': 'inactive_15',
 'Cited2_chr10_1253': 'inactive_16',
 'Cited2_chr10_1254': 'inactive_17',
 'Cited2_chr10_1267': 'inactive_18',
 'Col1a1_chr11_15258': 'inactive_19',
 'Col1a1_chr11_15259': 'inactive_20',
 'Col1a1_chr11_15270': 'inactive_21',
 'Col1a1_chr11_15275': 'inactive_22',
 'Col1a1_chr11_15276': 'inactive_23',
 'Col1a1_chr11_15301': 'inactive_24',
 'Col1a1_chr11_15307': 'inactive_25',
 'Col1a1_chr11_15316': 'inactive_26',
 'Col1a1_chr11_15322': 'inactive_27',
 'Col1a2_chr6_77': 'inactive_28',
 'Col1a2_chr6_93': 'inactive_29',
 'Col5a1_chr2_2558': 'inactive_30',
 'Col5a1_chr2_2565': 'inactive_31',
 'Col5a1_chr2_2571': 'inactive_32',
 'Col5a1_chr2_2575': 'inactive_33',
 'Col5a1_chr2_2576': 'inactive_34',
 'Epas1_chr17_10061': 'inactive_35',
 'Epas1_chr17_10063': 'inactive_36',
 'Epas1_chr17_10066': 'inactive_37',
 'Epas1_chr17_10070': 'inactive_38',
 'Epas1_chr17_10071': 'inactive_39',
 'Foxa2_chr2_13808': 'inactive_40',
 'Foxa2_chr2_13818': 'inactive_41',
 'Foxa2_chr2_13835': 'inactive_42',
 'Foxa2_chr2_13840': 'inactive_43',
 'Foxa2_chr2_13841': 'inactive_44',
 'Foxa2_chr2_13858': 'inactive_45',
 'Foxa2_chr2_13861': 'inactive_46',
 'Foxa2_chr2_13862': 'inactive_47',
 'Gata4_chr14_5677': 'inactive_48',
 'Gata4_chr14_5710': 'inactive_49',
 'Gata4_chr14_5714': 'inactive_50',
 'Gata4_chr14_5742': 'inactive_51',
 'Gata4_chr14_5749': 'inactive_52',
 'Gata4_chr14_5752': 'inactive_53',
 'Gata4_chr14_5763': 'inactive_54',
 'Gata4_chr14_5779': 'inactive_55',
 'Igfbp4_chr11_16710': 'inactive_56',
 'Igfbp4_chr11_16711': 'inactive_57',
 'Igfbp4_chr11_16716': 'inactive_58',
 'Igfbp4_chr11_16728': 'inactive_59',
 'Igfbp4_chr11_16735': 'inactive_60',
 'Igfbp4_chr11_16738': 'inactive_61',
 'Igfbp4_chr11_16740': 'inactive_62',
 'Igfbp4_chr11_16743': 'inactive_63',
 'Klf4_chr4_3934': 'inactive_64',
 'Klf4_chr4_3936': 'inactive_65',
 'Klf4_chr4_3946': 'inactive_66',
 'Klf4_chr4_3948': 'inactive_67',
 'Klf4_chr4_3949': 'inactive_68',
 'Klf4_chr4_3951': 'inactive_69',
 'Klf4_chr4_3952': 'inactive_70',
 'Lama1_chr17_7784': 'inactive_71',
 'Lama1_chr17_7788': 'inactive_72',
 'Lama1_chr17_7793': 'inactive_73',
 'Lama1_chr17_7814': 'inactive_74',
 'Lamb1_chr12_2183': 'inactive_75',
 'Lamb1_chr12_2186': 'inactive_76',
 'Lamb1_chr12_2210': 'inactive_77',
 'Lamb1_chr12_2215': 'inactive_78',
 'Lamb1_chr12_2216': 'inactive_79',
 'Lamb1_chr12_2238': 'inactive_80',
 'Lamb1_chr12_2239': 'inactive_81',
 'Lamb1_chr12_2296': 'inactive_82',
 'Lamc1_chr1_12127': 'inactive_83',
 'Lamc1_chr1_12152': 'inactive_84',
 'Lamc1_chr1_12175': 'inactive_85',
 'Lamc1_chr1_12185': 'inactive_86',
 'Lamc1_chr1_12193': 'inactive_87',
 'Lamc1_chr1_12201': 'inactive_88',
 'Map1b_chr13_9429': 'inactive_89',
 'Map1b_chr13_9445': 'inactive_90',
 'Map1b_chr13_9447': 'inactive_91',
 'Sox17_chr1_58': 'inactive_92',
 'Sox17_chr1_59': 'inactive_93',
 'Sox17_chr1_60': 'inactive_94',
 'Sox17_chr1_65': 'inactive_95',
 'Sox17_chr1_67': 'inactive_96',
 'Sox17_chr1_73': 'inactive_97',
 'Sox17_chr1_82': 'inactive_98',
 'Sox2_chr3_2005': 'inactive_99',
 'Sox2_chr3_2007': 'inactive_100',
 'Sox2_chr3_2008': 'inactive_101',
 'Sox2_chr3_2009': 'inactive_102',
 'Sox4_chr13_2052': 'inactive_103',
 'Sox4_chr13_2054': 'inactive_104',
 'Sox4_chr13_2055': 'inactive_105',
 'Sparc_chr11_7180': 'inactive_106',
 'Sparc_chr11_7195': 'inactive_107',
 'Sparc_chr11_7199': 'inactive_108',
 'Sparc_chr11_7203': 'inactive_109',
 'Sparc_chr11_7205': 'inactive_110',
 'Sparc_chr11_7210': 'inactive_111',
 'Sparc_chr11_7211': 'inactive_112',
 'Sparc_chr11_7230': 'inactive_113',
 'Sparc_chr11_7234': 'inactive_114',
 'Sparc_chr11_7235': 'inactive_115',
 'Sparc_chr11_7243': 'inactive_116',
 'Tgfbi_chr13_5692': 'inactive_117',
 'Tgfbi_chr13_5705': 'inactive_118',
 'Tgfbi_chr13_5724': 'inactive_119',
 'Tgfbi_chr13_5735': 'inactive_120',
 'Tgfbi_chr13_5741': 'inactive_121',
 'Tubb2b_chr13_2557': 'inactive_122',
 'Tubb2b_chr13_2568': 'inactive_123',
 'Tubb2b_chr13_2572': 'inactive_124',
 'Tubb2b_chr13_2576': 'inactive_125',
 'Tubb2b_chr13_2577': 'inactive_126',
 'Tubb2b_chr13_2580': 'inactive_127',
 'Tubb2b_chr13_2583': 'inactive_128',
 'Tubb2b_chr13_2590': 'inactive_129',
 'Txndc12_chr4_7951': 'inactive_130',
 'Txndc12_chr4_7961': 'inactive_131',
 'Txndc12_chr4_7962': 'inactive_132',
 'Txndc12_chr4_7973': 'inactive_133',
 'Txndc12_chr4_7978': 'inactive_134',
 'eef1aP': 'inactive_135',
 'pgk1P': 'inactive_136',
 'reference': 'inactive_137',
 'ubcP': 'inactive_138'}

In [10]:
minP=scm.SHENDURE_BOUNDS.reference_activity
inactive=vals.copy().drop(columns=["mu"])
inactive["cre_id"] = inactive["cre_id"].map(mapping)
inactive["mu"]=minP
inactive

           cre_id        cell_type        mu
0      inactive_0  SurfaceEctoderm  0.019311
1      inactive_1  SurfaceEctoderm  0.019311
2      inactive_2  SurfaceEctoderm  0.019311
3      inactive_3  SurfaceEctoderm  0.019311
4      inactive_4  SurfaceEctoderm  0.019311
..            ...              ...       ...
134  inactive_134  SurfaceEctoderm  0.019311
135  inactive_135  SurfaceEctoderm  0.019311
136  inactive_136  SurfaceEctoderm  0.019311
137  inactive_137  SurfaceEctoderm  0.019311
138  inactive_138  SurfaceEctoderm  0.019311

[139 rows x 3 columns]

This is 100%. Let us double to 200%...

In [11]:
# duplicated version with _b appended
inactive_b = inactive.copy()
inactive_b["cre_id"] = inactive_b["cre_id"] + "_b"

# stack them
inactive_double = pd.concat([inactive, inactive_b], ignore_index=True)
inactive_double

             cre_id        cell_type        mu
0        inactive_0  SurfaceEctoderm  0.019311
1        inactive_1  SurfaceEctoderm  0.019311
2        inactive_2  SurfaceEctoderm  0.019311
3        inactive_3  SurfaceEctoderm  0.019311
4        inactive_4  SurfaceEctoderm  0.019311
..              ...              ...       ...
273  inactive_134_b  SurfaceEctoderm  0.019311
274  inactive_135_b  SurfaceEctoderm  0.019311
275  inactive_136_b  SurfaceEctoderm  0.019311
276  inactive_137_b  SurfaceEctoderm  0.019311
277  inactive_138_b  SurfaceEctoderm  0.019311

[278 rows x 3 columns]

Then stack with original gt...

In [12]:
final_gt=pd.concat([vals,inactive_double],ignore_index=True).rename({"mu":"true_mean"},axis=1)
final_gt

              cre_id        cell_type  true_mean
0    Bend5_chr4_8168  SurfaceEctoderm   0.019097
1    Bend5_chr4_8174  SurfaceEctoderm    0.01163
2    Bend5_chr4_8175  SurfaceEctoderm   0.671256
3    Bend5_chr4_8179  SurfaceEctoderm   0.019683
4    Bend5_chr4_8199  SurfaceEctoderm   0.004408
..               ...              ...        ...
412   inactive_134_b  SurfaceEctoderm   0.019311
413   inactive_135_b  SurfaceEctoderm   0.019311
414   inactive_136_b  SurfaceEctoderm   0.019311
415   inactive_137_b  SurfaceEctoderm   0.019311
416   inactive_138_b  SurfaceEctoderm   0.019311

[417 rows x 3 columns]

In [13]:
assert len(final_gt[["cre_id","cell_type"]].drop_duplicates()) == len(final_gt)

# Creating artificial libraries

In [14]:
libraries=[scm.simulate_library(CREs=final_gt["cre_id"],
                 library_model=scm.SHENDURE_BOUNDS.library_model)
                 for i in range(5)]

In [15]:
libraries[2]

                cre_id               mpra_bc  abundance
0      Bend5_chr4_8168  AAAAAAAAAAAAAAAAAAAA   0.000013
1      Bend5_chr4_8168  AAAAAAAAAAAAAAAAAAAC   0.000002
2      Bend5_chr4_8168  AAAAAAAAAAAAAAAAAAAG   0.000013
3      Bend5_chr4_8168  AAAAAAAAAAAAAAAAAAAT   0.000047
4      Bend5_chr4_8168  AAAAAAAAAAAAAAAAAACA   0.000024
...                ...                   ...        ...
55875   inactive_138_b  AAAAAAAAAAAATCGGCAAT   0.000010
55876   inactive_138_b  AAAAAAAAAAAATCGGCACA   0.000005
55877   inactive_138_b  AAAAAAAAAAAATCGGCACC   0.000009
55878   inactive_138_b  AAAAAAAAAAAATCGGCACG   0.000014
55879   inactive_138_b  AAAAAAAAAAAATCGGCACT   0.000002

[55880 rows x 3 columns]

In [16]:
final_gt.dtypes

cre_id                     object
cell_type                  object
true_mean    Sparse[float64, 1.0]
dtype: object

# Creating sim

In [28]:
sim=scm.de_novo_simulation(location=data_root,
                            name="twothird_pow_sim_2026-01-22",
                            client=client,
                            libraries=libraries,
                            library_mapping="corresponding",
                            n_sims=5,
                            experiment_bounds=scm.SHENDURE_BOUNDS,
                            ground_truth=final_gt)

scMPRAforge: INFO: No 'state.parquet' found for 'twothird_pow_sim_2026-01-22'. Initalizing new object.

In [ ]:
sim.gamut()

scMPRAforge: INFO: A: drawn_library cols: Index(['Unnamed: 0', 'cre_id', 'mpra_bc', 'abundance'], dtype='object'), types: Unnamed: 0      int64
cre_id         object
mpra_bc        object
abundance     float64
dtype: object
scMPRAforge: INFO: A: cells_df cols: Index(['cell_type', 'cell_bc'], dtype='object'), types: cell_type    object
cell_bc      object
dtype: object
scMPRAforge: INFO: B: cells_df cols: Index(['cell_type', 'cell_bc', 'Unnamed: 0', 'cre_id', 'mpra_bc', 'abundance'], dtype='object'), types: cell_type      object
cell_bc        object
Unnamed: 0      int64
cre_id         object
mpra_bc        object
abundance     float64
dtype: object
scMPRAforge: INFO: A: drawn_library cols: Index(['Unnamed: 0', 'cre_id', 'mpra_bc', 'abundance'], dtype='object'), types: Unnamed: 0      int64
cre_id         object
mpra_bc        object
abundance     float64
dtype: object
scMPRAforge: INFO: A: cells_df cols: Index(['cell_type', 'cell_bc'], dtype='object'), types: cell_type    object
cell_bc      object
dtype: object
scMPRAforge: INFO: A: drawn_library cols: Index(['Unnamed: 0', 'cre_id', 'mpra_bc', 'abundance'], dtype='object'), types: Unnamed: 0      int64
cre_id         object
mpra_bc        object
abundance     float64
dtype: object
scMPRAforge: INFO: A: cells_df cols: Index(['cell_type', 'cell_bc'], dtype='object'), types: cell_type    object
cell_bc      object
dtype: object
scMPRAforge: INFO: B: cells_df cols: Index(['cell_type', 'cell_bc', 'Unnamed: 0', 'cre_id', 'mpra_bc', 'abundance'], dtype='object'), types: cell_type      object
cell_bc        object
Unnamed: 0      int64
cre_id         object
mpra_bc        object
abundance     float64
dtype: object
scMPRAforge: INFO: B: cells_df cols: Index(['cell_type', 'cell_bc', 'Unnamed: 0', 'cre_id', 'mpra_bc', 'abundance'], dtype='object'), types: cell_type      object
cell_bc        object
Unnamed: 0      int64
cre_id         object
mpra_bc        object
abundance     float64
dtype: object
scMPRAforge: INFO: A: drawn_library cols: Index(['Unnamed: 0', 'cre_id', 'mpra_bc', 'abundance'], dtype='object'), types: Unnamed: 0      int64
cre_id         object
mpra_bc        object
abundance     float64
dtype: object
scMPRAforge: INFO: A: cells_df cols: Index(['cell_type', 'cell_bc'], dtype='object'), types: cell_type    object
cell_bc      object
dtype: object
scMPRAforge: INFO: B: cells_df cols: Index(['cell_type', 'cell_bc', 'Unnamed: 0', 'cre_id', 'mpra_bc', 'abundance'], dtype='object'), types: cell_type      object
cell_bc        object
Unnamed: 0      int64
cre_id         object
mpra_bc        object
abundance     float64
dtype: object
scMPRAforge: INFO: C: cells_df cols: Index(['cell_type', 'cell_bc', 'Unnamed: 0', 'cre_id', 'mpra_bc'], dtype='object'), types: cell_type     string[python]
cell_bc               object
Unnamed: 0             int64
cre_id        string[python]
mpra_bc               object
dtype: object
scMPRAforge: INFO: C: cells_df cols: Index(['cell_type', 'cell_bc', 'Unnamed: 0', 'cre_id', 'mpra_bc'], dtype='object'), types: cell_type     string[python]
cell_bc               object
Unnamed: 0             int64
cre_id        string[python]
mpra_bc               object
dtype: object
scMPRAforge: INFO: C: cells_df cols: Index(['cell_type', 'cell_bc', 'Unnamed: 0', 'cre_id', 'mpra_bc'], dtype='object'), types: cell_type     string[python]
cell_bc               object
Unnamed: 0             int64
cre_id        string[python]
mpra_bc               object
dtype: object
scMPRAforge: INFO: C: cells_df cols: Index(['cell_type', 'cell_bc', 'Unnamed: 0', 'cre_id', 'mpra_bc'], dtype='object'), types: cell_type     string[python]
cell_bc               object
Unnamed: 0             int64
cre_id        string[python]
mpra_bc               object
dtype: object
scMPRAforge: INFO: D: cells_df cols: Index(['cell_type', 'cell_bc', 'Unnamed: 0_x', 'cre_id', 'mpra_bc',
       'Unnamed: 0_y', 'true_mean'],
      dtype='object'), types: cell_type       string[python]
cell_bc                 object
Unnamed: 0_x             int64
cre_id          string[python]
mpra_bc                 object
Unnamed: 0_y           float64
true_mean              float64
dtype: object
scMPRAforge: INFO: D 1370348
scMPRAforge: INFO: D: cells_df cols: Index(['cell_type', 'cell_bc', 'Unnamed: 0_x', 'cre_id', 'mpra_bc',
       'Unnamed: 0_y', 'true_mean'],
      dtype='object'), types: cell_type       string[python]
cell_bc                 object
Unnamed: 0_x             int64
cre_id          string[python]
mpra_bc                 object
Unnamed: 0_y           float64
true_mean              float64
dtype: object
scMPRAforge: INFO: D: cells_df cols: Index(['cell_type', 'cell_bc', 'Unnamed: 0_x', 'cre_id', 'mpra_bc',
       'Unnamed: 0_y', 'true_mean'],
      dtype='object'), types: cell_type       string[python]
cell_bc                 object
Unnamed: 0_x             int64
cre_id          string[python]
mpra_bc                 object
Unnamed: 0_y           float64
true_mean              float64
dtype: object
scMPRAforge: INFO: D: cells_df cols: Index(['cell_type', 'cell_bc', 'Unnamed: 0_x', 'cre_id', 'mpra_bc',
       'Unnamed: 0_y', 'true_mean'],
      dtype='object'), types: cell_type       string[python]
cell_bc                 object
Unnamed: 0_x             int64
cre_id          string[python]
mpra_bc                 object
Unnamed: 0_y           float64
true_mean              float64
dtype: object
scMPRAforge: INFO: D 1380338
scMPRAforge: INFO: D 1379554
scMPRAforge: INFO: D 1375432
scMPRAforge: INFO: [debug] dumped df to: debug_df_a3606e2bf4eb49d09514f3d0b4d64463.tsv.gz
scMPRAforge: INFO: [debug] dumped df to: debug_df_e27c2344c0364b1abd7499ed4fd84be2.tsv.gz
scMPRAforge: INFO: [debug] dumped df to: debug_df_03ac43b3023c423bac1221874de7b1e2.tsv.gz
2026-01-23 14:38:45,127 - distributed.worker - ERROR - Compute Failed
Key:       _simulate_transfection_helper-a8ea31152b396ead45e9594addf59592
State:     executing
Task:  <Task '_simulate_transfection_helper-a8ea31152b396ead45e9594addf59592' _simulate_transfection_helper(, ...)>
Exception: "AssertionError('DataFrame contains NA values in these rows:\\n             cell_type               cell_bc  ...  Unnamed: 0_y true_mean\\n0       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...           NaN       NaN\\n1       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...           NaN       NaN\\n2       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...           NaN       NaN\\n3       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...           NaN       NaN\\n4       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...           NaN       NaN\\n...                ...                   ...  ...           ...       ...\\n777931       reference  AAAAAAAAAAAAGGGCCTTA  ...           NaN       NaN\\n777932       reference  AAAAAAAAAAAAGGGCCTTA  ...           NaN       NaN\\n777933       reference  AAAAAAAAAAAAGGGCCTTA  ...           NaN       NaN\\n777934       reference  AAAAAAAAAAAAGGGCCTTA  ...           NaN       NaN\\n777935       reference  AAAAAAAAAAAAGGGCCTTA  ...           NaN       NaN\\n\\n[685174 rows x 7 columns]\\n\\nCheck that cell type & CRE names match across parameters.')"
Traceback: '  File "/nfs/roberts/project/pi_skr2/mcn26/tabula-rasa/notebooks/object_creation/simulations/emperically_calibrated/shendure/scMPRAforge/core.py", line 5074, in _simulate_transfection_helper\n    transfected=_simulate_transfection(\n  File "/nfs/roberts/project/pi_skr2/mcn26/tabula-rasa/notebooks/object_creation/simulations/emperically_calibrated/shendure/scMPRAforge/core.py", line 5823, in _simulate_transfection\n    working=_simulate_single_replicate_transfection()\n  File "/nfs/roberts/project/pi_skr2/mcn26/tabula-rasa/notebooks/object_creation/simulations/emperically_calibrated/shendure/scMPRAforge/core.py", line 5809, in _simulate_single_replicate_transfection\n    assert bad.empty, (\n'

scMPRAforge: INFO: [debug] dumped df to: debug_df_f8d9a3a642a543748bd593e65692fc34.tsv.gz
2026-01-23 14:38:45,354 - distributed.worker - ERROR - Compute Failed
Key:       _simulate_transfection_helper-691efded897f635165388cb42b5cabbf
State:     executing
Task:  <Task '_simulate_transfection_helper-691efded897f635165388cb42b5cabbf' _simulate_transfection_helper(, ...)>
Exception: "AssertionError('DataFrame contains NA values in these rows:\\n             cell_type               cell_bc  ...  Unnamed: 0_y true_mean\\n0       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...           NaN       NaN\\n1       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...           NaN       NaN\\n2       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAC  ...           NaN       NaN\\n3       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAC  ...           NaN       NaN\\n4       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAC  ...           NaN       NaN\\n...                ...                   ...  ...           ...       ...\\n782933       reference  AAAAAAAAAAAAGGGCCTTA  ...           NaN       NaN\\n782934       reference  AAAAAAAAAAAAGGGCCTTA  ...           NaN       NaN\\n782935       reference  AAAAAAAAAAAAGGGCCTTA  ...           NaN       NaN\\n782936       reference  AAAAAAAAAAAAGGGCCTTA  ...           NaN       NaN\\n782937       reference  AAAAAAAAAAAAGGGCCTTA  ...           NaN       NaN\\n\\n[690169 rows x 7 columns]\\n\\nCheck that cell type & CRE names match across parameters.')"
Traceback: '  File "/nfs/roberts/project/pi_skr2/mcn26/tabula-rasa/notebooks/object_creation/simulations/emperically_calibrated/shendure/scMPRAforge/core.py", line 5074, in _simulate_transfection_helper\n    transfected=_simulate_transfection(\n  File "/nfs/roberts/project/pi_skr2/mcn26/tabula-rasa/notebooks/object_creation/simulations/emperically_calibrated/shendure/scMPRAforge/core.py", line 5823, in _simulate_transfection\n    working=_simulate_single_replicate_transfection()\n  File "/nfs/roberts/project/pi_skr2/mcn26/tabula-rasa/notebooks/object_creation/simulations/emperically_calibrated/shendure/scMPRAforge/core.py", line 5809, in _simulate_single_replicate_transfection\n    assert bad.empty, (\n'

2026-01-23 14:38:45,400 - distributed.worker - ERROR - Compute Failed
Key:       _simulate_transfection_helper-d1305514d300e7db58f6263577905dd9
State:     executing
Task:  <Task '_simulate_transfection_helper-d1305514d300e7db58f6263577905dd9' _simulate_transfection_helper(, ...)>
Exception: "AssertionError('DataFrame contains NA values in these rows:\\n             cell_type               cell_bc  ...  Unnamed: 0_y true_mean\\n0       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...           NaN       NaN\\n1       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...           NaN       NaN\\n2       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...           NaN       NaN\\n3       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...           NaN       NaN\\n4       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...           NaN       NaN\\n...                ...                   ...  ...           ...       ...\\n782006       reference  AAAAAAAAAAAAGGGCCTTA  ...           NaN       NaN\\n782007       reference  AAAAAAAAAAAAGGGCCTTA  ...           NaN       NaN\\n782008       reference  AAAAAAAAAAAAGGGCCTTA  ...           NaN       NaN\\n782009       reference  AAAAAAAAAAAAGGGCCTTA  ...           NaN       NaN\\n782010       reference  AAAAAAAAAAAAGGGCCTTA  ...           NaN       NaN\\n\\n[687716 rows x 7 columns]\\n\\nCheck that cell type & CRE names match across parameters.')"
Traceback: '  File "/nfs/roberts/project/pi_skr2/mcn26/tabula-rasa/notebooks/object_creation/simulations/emperically_calibrated/shendure/scMPRAforge/core.py", line 5074, in _simulate_transfection_helper\n    transfected=_simulate_transfection(\n  File "/nfs/roberts/project/pi_skr2/mcn26/tabula-rasa/notebooks/object_creation/simulations/emperically_calibrated/shendure/scMPRAforge/core.py", line 5823, in _simulate_transfection\n    working=_simulate_single_replicate_transfection()\n  File "/nfs/roberts/project/pi_skr2/mcn26/tabula-rasa/notebooks/object_creation/simulations/emperically_calibrated/shendure/scMPRAforge/core.py", line 5809, in _simulate_single_replicate_transfection\n    assert bad.empty, (\n'

2026-01-23 14:38:45,568 - distributed.worker - ERROR - Compute Failed
Key:       _simulate_transfection_helper-6408bc2f1dc58ba88d7a008c44471678
State:     executing
Task:  <Task '_simulate_transfection_helper-6408bc2f1dc58ba88d7a008c44471678' _simulate_transfection_helper(, ...)>
Exception: "AssertionError('DataFrame contains NA values in these rows:\\n             cell_type               cell_bc  ...  Unnamed: 0_y true_mean\\n0       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...           NaN       NaN\\n1       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...           NaN       NaN\\n2       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...           NaN       NaN\\n3       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...           NaN       NaN\\n4       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...           NaN       NaN\\n...                ...                   ...  ...           ...       ...\\n782041       reference  AAAAAAAAAAAAGGGCCTTA  ...           NaN       NaN\\n782042       reference  AAAAAAAAAAAAGGGCCTTA  ...           NaN       NaN\\n782043       reference  AAAAAAAAAAAAGGGCCTTA  ...           NaN       NaN\\n782044       reference  AAAAAAAAAAAAGGGCCTTA  ...           NaN       NaN\\n782045       reference  AAAAAAAAAAAAGGGCCTTA  ...           NaN       NaN\\n\\n[689777 rows x 7 columns]\\n\\nCheck that cell type & CRE names match across parameters.')"
Traceback: '  File "/nfs/roberts/project/pi_skr2/mcn26/tabula-rasa/notebooks/object_creation/simulations/emperically_calibrated/shendure/scMPRAforge/core.py", line 5074, in _simulate_transfection_helper\n    transfected=_simulate_transfection(\n  File "/nfs/roberts/project/pi_skr2/mcn26/tabula-rasa/notebooks/object_creation/simulations/emperically_calibrated/shendure/scMPRAforge/core.py", line 5823, in _simulate_transfection\n    working=_simulate_single_replicate_transfection()\n  File "/nfs/roberts/project/pi_skr2/mcn26/tabula-rasa/notebooks/object_creation/simulations/emperically_calibrated/shendure/scMPRAforge/core.py", line 5809, in _simulate_single_replicate_transfection\n    assert bad.empty, (\n'

scMPRAforge: INFO: A: drawn_library cols: Index(['Unnamed: 0', 'cre_id', 'mpra_bc', 'abundance'], dtype='object'), types: Unnamed: 0      int64
cre_id         object
mpra_bc        object
abundance     float64
dtype: object
scMPRAforge: INFO: A: cells_df cols: Index(['cell_type', 'cell_bc'], dtype='object'), types: cell_type    object
cell_bc      object
dtype: object
scMPRAforge: INFO: B: cells_df cols: Index(['cell_type', 'cell_bc', 'Unnamed: 0', 'cre_id', 'mpra_bc', 'abundance'], dtype='object'), types: cell_type      object
cell_bc        object
Unnamed: 0      int64
cre_id         object
mpra_bc        object
abundance     float64
dtype: object
scMPRAforge: INFO: C: cells_df cols: Index(['cell_type', 'cell_bc', 'Unnamed: 0', 'cre_id', 'mpra_bc'], dtype='object'), types: cell_type     string[python]
cell_bc               object
Unnamed: 0             int64
cre_id        string[python]
mpra_bc               object
dtype: object
scMPRAforge: INFO: D: cells_df cols: Index(['cell_type', 'cell_bc', 'Unnamed: 0_x', 'cre_id', 'mpra_bc',
       'Unnamed: 0_y', 'true_mean'],
      dtype='object'), types: cell_type       string[python]
cell_bc                 object
Unnamed: 0_x             int64
cre_id          string[python]
mpra_bc                 object
Unnamed: 0_y           float64
true_mean              float64
dtype: object
scMPRAforge: INFO: D 1385726
scMPRAforge: INFO: [debug] dumped df to: debug_df_76e8cbb8895d45e4940bc8f32174d385.tsv.gz
2026-01-23 14:38:51,922 - distributed.worker - ERROR - Compute Failed
Key:       _simulate_transfection_helper-b9de56b490eaee91a316166825d53710
State:     executing
Task:  <Task '_simulate_transfection_helper-b9de56b490eaee91a316166825d53710' _simulate_transfection_helper(, ...)>
Exception: "AssertionError('DataFrame contains NA values in these rows:\\n             cell_type               cell_bc  ...  Unnamed: 0_y true_mean\\n0       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...           NaN       NaN\\n1       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...           NaN       NaN\\n2       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...           NaN       NaN\\n3       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...           NaN       NaN\\n4       Cardiomyocytes  AAAAAAAAAAAAAAAAAAAA  ...           NaN       NaN\\n...                ...                   ...  ...           ...       ...\\n785711       reference  AAAAAAAAAAAAGGGCCTTA  ...           NaN       NaN\\n785712       reference  AAAAAAAAAAAAGGGCCTTA  ...           NaN       NaN\\n785713       reference  AAAAAAAAAAAAGGGCCTTA  ...           NaN       NaN\\n785714       reference  AAAAAAAAAAAAGGGCCTTA  ...           NaN       NaN\\n785715       reference  AAAAAAAAAAAAGGGCCTTA  ...           NaN       NaN\\n\\n[692863 rows x 7 columns]\\n\\nCheck that cell type & CRE names match across parameters.')"
Traceback: '  File "/nfs/roberts/project/pi_skr2/mcn26/tabula-rasa/notebooks/object_creation/simulations/emperically_calibrated/shendure/scMPRAforge/core.py", line 5074, in _simulate_transfection_helper\n    transfected=_simulate_transfection(\n  File "/nfs/roberts/project/pi_skr2/mcn26/tabula-rasa/notebooks/object_creation/simulations/emperically_calibrated/shendure/scMPRAforge/core.py", line 5823, in _simulate_transfection\n    working=_simulate_single_replicate_transfection()\n  File "/nfs/roberts/project/pi_skr2/mcn26/tabula-rasa/notebooks/object_creation/simulations/emperically_calibrated/shendure/scMPRAforge/core.py", line 5809, in _simulate_single_replicate_transfection\n    assert bad.empty, (\n'

In [19]:
#sim.save()

In [20]:
#sim

Make the hypotheses...

In [21]:
#spread_hypothesis.to_tsv(f"{data_root}/pow_sim_2026-01-03_hypo.tsv")
#hs_all_cre = scm.make_all_by_cre_hypotheses(
#    counts=demo_counts,
#    reference_cell_type="reference",
#)

In [22]:
sim.ground_truth.dtypes

cre_id             string[python]
cell_type          string[python]
true_mean    Sparse[float64, 1.0]
dtype: object

In [30]:
#client.close()
#cluster.close()