This notebook generates n simulated replicates of the shendure dataset. As though the whole experiment were run n more times.

Imports

In [1]:
import scMPRAforge as scm
from dask.distributed import Client, LocalCluster

2025-11-11 10:19:43.663360: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-11-11 10:19:43.666703: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /apps/software/2024a/software/code-server/4.103.0/lib:/apps/software/2024a/software/gettext/0.22.5-GCCcore-13.3.0/lib:/apps/software/2024a/software/libiconv/1.17-GCCcore-13.3.0/lib:/apps/software/2024a/software/ncurses/6.5-GCCcore-13.3.0/lib:/apps/software/2024a/software/libxml2/2.12.7-GCCcore-13.3.0/lib:/apps/software/2024a/software/XZ/5.4.5-GCCcore-13.3.0/lib:/apps/software/2024a/software/expat/2.6.2-GCCcore-13.3.0/lib:/apps/software/2024a/software/cURL/8.7.1-GCCcore-13.3.0/lib:/apps/software/2024a/software/OpenSSL/3/lib64:/apps/software/2024a/software/zlib/1.3.1-GCCcore-13.3.0/lib:/apps/software/2024a/software/GCCcore/13.3.0/lib64
2025-11-11 10:19:43.666714: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

In [ ]:
%load_ext autoreload
%autoreload 2

Set up cluster

In [ ]:
cluster=LocalCluster(memory_limit='8GB')
client=Client(cluster)

BokehUserWarning: reference already known 'p1011'
BokehUserWarning: reference already known 'p1051'
BokehUserWarning: reference already known 'p1289'
BokehUserWarning: reference already known 'p1295'
BokehUserWarning: reference already known 'p1353'
2025-11-11 10:27:37,239 - distributed.scheduler - WARNING - Removing worker 'tcp://127.0.0.1:34077' caused the cluster to lose already computed task(s), which will be recomputed elsewhere: {'lambda-8b0603407ace033f883e7a992b36cd08', 'lambda-e652c1ce5d5f9f942059c2de2a79d6d6', 'lambda-1cbeeb7dfb50490ff79917263efbe1a5', 'lambda-692c1deebe4af2d4290cd03f0c3fe372', 'lambda-998236f60e1d15b0b7553255cb58be73', 'lambda-fc6712c277e1222db2b8a98e4c78c1b7', 'lambda-f33b8754a91d03451f1449d6e3502ba2', 'lambda-f779afc13fd8f79e267dbcd97c57eacb', 'lambda-0cf08a330482229c42696883dba38505', 'lambda-11c6ffaf17b450a929de9f590fb4c186', 'lambda-9a23d9c814d6775c78c91e333ddafb78', 'lambda-7166d4de39108cbbcdce6e96d49c4db4', 'lambda-b6f2872d772682126c7318f8f7837a2e', 'lambda-cd6b6af60ff93d9cb202996e519da161', 'lambda-e7dd053e69a9fcd8b7a2662422e98b7d', 'lambda-480adc52a88b81f03ebafe22c285ef4f', 'lambda-79d13eac7104669d4dc3fe475281e08b', 'lambda-de1def61880b135e97be2503e3095e4c', 'lambda-7117448494b35bc147cf9540c680c589', 'lambda-d5c1cd4ecb848bb09bd29b66968b48d9', 'lambda-ac2372e8557b898c75b371eab127b6e8', 'lambda-c2d87dc09abe306a773f5b34bf2b8835', 'lambda-d44aee8d21e7ac8c34ede35cf781fcca', 'lambda-c763d5447a12d98e3eb51e6792837c2f', 'lambda-42955657db1d9d8baf62c37a494959d5', 'lambda-b20f3a449e44430997267844a55a7712', 'lambda-5d39df219b0d2fea73a7478860acf251', 'lambda-3b88b0f34a1375e96751384996be1da2', 'lambda-fb1b9bcd859dfbda7513c95ccebddf11', 'lambda-df31bd9c9aabc1d99652ea9f84ec75e9', 'lambda-ed1013f5458ad0051fdf4aaa6114873f', 'lambda-c6f4d4e1ff2ef88fabaa7bb8a8c975d5', 'lambda-27676fe794179dd17665f83a4bbe0a43', 'lambda-e95b08e88b83fcc640b24025a326778d', 'lambda-59fd40404571cdafe21d95aeb87ced36', 'lambda-ff677fa8b1a53c43f9cd048a67fdae25', 'lambda-fe21784e731459fe855e651c14451896', 'lambda-7b016611634cce41dc6f112361763e91', 'lambda-f0f58bfdbc0c70b5f7d8003dc42f7c08', 'lambda-6672945141a115b21d927527178dd566', 'lambda-0027f0b13031a48d31161974a3c86134', 'lambda-7c64a7e5c7d35b0cf732f11d49c22176', 'lambda-f843c351347f3230ffc0ab6cfc1b75b6', 'lambda-5fdf43be6c94554979b07841aeec6589', 'lambda-7f5e53e79747050feefb2bfc05e2c843', 'lambda-c4165b6c4950e624aa465786946bf437', 'lambda-6258dc25be1af03546e771d97cf9e692', 'lambda-0bce191036fa343e157bc8c109e7cfbc', 'lambda-65dd2d7ac80069fde6e4642a4b72d2ce', 'lambda-a1e180d6fc323bd661d995792059dbc0', 'lambda-b7cff1a944cdca5881436ecde822c214', 'lambda-ad0cb13556a8e506c9ee02841af5920b', 'lambda-07381c16e2306aa93b627a8ed5013634', 'lambda-59375627bcb1782896f3284335951b31', 'lambda-e645bb14eb3a38b4d97e3acab0f32289', 'lambda-90b88204fe0f3ab391f10be7c7069d05', 'lambda-e584e0d349e9e5082a745e0e0d4ed710', 'lambda-c255604b5c25d7e80236f4241ef1451b', 'lambda-e84c2b0af40abd3d555743c787813acc', 'lambda-35334bdc5ea676b51b5f3406f0b69727', 'lambda-6be83b510719ea1053a6f5024401ffc3', 'lambda-0ce037f6624c8eafa159939e1ec967ec', 'lambda-c1b010ca050afe4c7b5fbb2545b5e436', 'lambda-72f0b147cb2025657102c53c81d7a571', 'lambda-61fc4f0c219e9d1141e8189940d485f9', 'lambda-2533ad675b683f96c379914a70960aa6', 'lambda-89045a5a48786196757233f1e6073e0d', 'lambda-7c472c0c9d78944910d9488c1f1356e4', 'lambda-abd3a8f8089f9528b91d68b65f79ef3e', 'lambda-8c15b4fa54107999231d7e3949f8ea3d', 'lambda-0337be6c919c036131016723b6bc9288', 'lambda-c10480bceac9ef86c0c230951cc46dfc', 'lambda-c093d1446abccdda3a47b3165ebd4a1e', 'lambda-31c7d40b6341eecb42f313e139ef8a05', 'lambda-8b6d0155fca8e71f36bfe2c712bea5bd', 'lambda-00ff8d6285a8dee085ba13a7a2f8ccf1', 'lambda-f58117c9f51786b34a34bd09e00fa739', 'lambda-1f35af4545b2010a4d7c884c0ca08675', 'lambda-8f9f45b6aa827a8ed3776f6a3ab1c3ba', 'lambda-cc90e2a5ed1c7adbeabb66f26d94f951', 'lambda-65e5d3317d6af94ff5fed07bef7931f9', 'lambda-a4b2750f5c94973c2e32c6a0b1c46866', 'lambda-bae10848143106f6b8da0abc8ab9c74c', 'lambda-beb690b2bcaac0843c37344ca9163776', 'lambda-59a4fa51ba81d87b268f460ae534527a', 'lambda-660529a0a64f4c51d2dd90b53d445fec', 'lambda-6994ea5e7c69e63454ff66d30cd844fd', 'lambda-80dc331da65d832376180b6ec9fae812', 'lambda-43d0e8091737b7782eec5d28e598d108', 'lambda-2663f6ce133a7178c91b29c79ac6fcee', 'lambda-c53127b7369690f50a051c21612fb9e5', 'lambda-c10975b5f13d2f05221a765ffd8c9a92', 'lambda-baae953cb29771d583b789fcf0245967', 'lambda-dcb91616daac22ea069c618d74b39587', 'lambda-46606574e38f77009a63f50da44733ed', 'lambda-2b95a27838805fad996d5558c5c06632', 'lambda-4738512a3274ae69fb201cf7c7e007ec', 'lambda-dd35a22ffb4890a6ebf70cb374ae5ae1', 'lambda-a7857b1d457d9bef62bc66340628f5c7', 'lambda-eaa31ac479be98696b3000b0578374ce', 'lambda-b8fad43a81134895348254b9e8ffb1eb', 'lambda-5b287a1ad03a42cdb008662dd05a08fb', 'lambda-b2e76795f165ece1aa86a860542d7730', 'lambda-334d093a39e109d8af2f3556779f9a22', 'lambda-c0dd8eb11e2bdd4c326656fba22c78a3', 'lambda-ebdbb91ccc4b9f01f6a0ce283cf43316', 'lambda-1275a4d7b1ad216891ea773bd7daad4e', 'lambda-0b76d9190f29d2240b8965b321e02b71', 'lambda-8cce5a55832bbd036febfd4d285f4a1b', 'lambda-ff81ebef29369bec2274554d4f59994e', 'lambda-da500084c4d06ac6ef2218dd065a38bb', 'lambda-28f7eb232926513e97fa65a19fa97bf2', 'lambda-55f32bd83fb9af98892eafebe739eec6', 'lambda-96fcee7753fba1246ced8565db18925e', 'lambda-17434d74c661aec822733c6418051f48', 'lambda-f3a0ea3940e189f3b9fe00d2d2a828d7', 'lambda-b6eb9fca02925b8c26ad9acf9bf329a2', 'lambda-47a37303d2cc137cf40781e0db99f8c4', 'lambda-1532799416121ac0e4ca15c5d926d39d', 'lambda-192ac6c3258a533395802004a1498fb7', '_wrap_helper-c34208fca89f49a514ed9388b83541ab', 'lambda-7c872b5051a42b8a78676f9bb36ed104', 'lambda-523fc0c046c439853483661336785a09', 'lambda-4a5fb8fb672661439ee418d04ea72ec1', 'lambda-57bbacde576a9cf5428dac9734354f1c', 'lambda-2573320630aca78ad08bc1e65977eabe', 'lambda-8e4fdd7ec0689bc88eed12a82b8efe72', 'lambda-0ba1070cbd3254acd5aafbb60270843c', 'lambda-0f1d22dc628c3baf98f227c2f6ac15ac', 'lambda-d1d66310a91455dde031d0e24ad6a46d', 'lambda-eb051a0bfd74709ded385edfeada961f', 'lambda-18c1aa467ad3ba8c548378f02c4b4dec', 'lambda-a03623e8491cf9dd14ab35d36cf9b221', 'lambda-431955ce4ce6601f98eee661d736d28e', 'lambda-31ed7ac2133506783ea31b53e27781bd', 'lambda-125a287b86ce114f214b0316ebe3111c', 'lambda-2410c8d7c6a7f88974ac9a22edcfec0e', 'lambda-11790dba53f5466bac0b1a86b292b289', 'lambda-5cbb66197f28fbf3e602b92c9facf96d', 'lambda-5b06bc4550d501c3042ae85fea210744', 'lambda-e6facb42404f826b6eaba2307fd9fe7e', 'lambda-a9d2bde4fe1f10ded1b0101b059281fb', 'lambda-63e92a4936a7761bfca8fd13d4dcbb67', 'lambda-7067e91a1cc97f4e5a7f832db92ce46c', 'lambda-2b889143df80e2bebfd258ac7263ea8d', 'lambda-8c01f301ecb1282fc6c5d63a012e08a3', 'lambda-86220f543dae08bef91e9c77d23e1df0', 'lambda-0c7fc9a5cbc853f400458fae866abec7', 'lambda-4f298c1c56e048892eb035b1d728dd25', 'lambda-dbe778e5223436dd70bef87dd527bd08', 'lambda-fccf65dbe04d6f6806d45fac130b04c0', 'lambda-11db0ff7d91a16413e17c7bef2d1e067', 'lambda-c968f702c8ae5d475c175e661a04f5c1', 'lambda-d6593e54eface4fce9487a04aefe1069', 'lambda-5e45cc0e461ad09c1f144dbd19e8b940', 'lambda-585e53674f286480ab12843fcc2faf8e', 'lambda-6892092d3c28695682cb24a3d7199af1', 'lambda-17feac49b22cd8987be35fd6695d73a9', 'lambda-669d0acb4c5fd426ed674f4eab0e4652', 'lambda-8aa7816d04ffdf96f4afb5651eeecd8d', 'lambda-3226834284eb9b5f20cbb96869df82a1', 'lambda-98270c918cae06c5cad0c131fd52d547', 'lambda-c80f99039febba8b039f639236f057cf', 'lambda-559c064785f8b3abd0da7fe1685ffa1c', 'lambda-ae1ffa92ebfe3eba1e1fdcb7d1f56f7c', 'lambda-5d9b6687dea2e5e8724af2d94c92fa3a', 'lambda-044a08a5b0c31d009262c88bbea17da0', 'lambda-c37394eda5f138d24130b8f3d6dece0e', 'lambda-aae40d70453bb282b05f9ca00b3c68a1', 'lambda-115ff8a383cb6a96c4210817a805941c', 'lambda-94c1aff2590ddfec31b61af4424edc12', 'lambda-241e025e7aaefd67a4a14882f2598958', 'lambda-3d89a5d26e2e517042237c445fa89f30', 'lambda-2d0528680aa6a7862b7d8dd5f64c7adf', 'lambda-ff12c617fc561953996ea64f5da3b701', 'lambda-ba522cf57cd813026f4b3305f1dd7c1c', 'lambda-05ee1a99ef78b8a7fc17ffa34cc4ffa2', 'lambda-2af1c871e8b5d421ee7e385b148dcb8e', 'lambda-48e73c0d79039e26a904805514724a45', 'lambda-514fe0e5f4814706f2c931b22a8e1fde', 'lambda-46ec35b77f33e2e47aedbff2c9bc1ab6', 'lambda-d58837b9f14a21a7b5388621f18cc770', 'lambda-1173595b3ae705a5fab1c72c6352eeb4', 'lambda-cc647eec2b3d3b22f1838924a82790e6', 'lambda-b1071f4b2311d322e1fa47af42e5e235', 'lambda-e787946c0f07e2b032b1895476df702b', 'lambda-13c540ff31bdc0f8958b8cdd27f76f38', 'lambda-f5a15f2883f9d6777ed28caff1e27bf3', 'lambda-abf35539ec58d92161aa4c234dcb563f', 'lambda-9dc5cb2aef9b112514ec0a2e2b30c4fd', 'lambda-42437077790d87d101e4b7f28b559406', 'lambda-1cc847cf950c61ab87495c6012f35ad6'} (stimulus_id='handle-worker-cleanup-1762874857.238797')

In [3]:
client.dashboard_link

'http://127.0.0.1:8787/status'

Load shendure ortho

In [4]:
name="ortho_primordial_intercept"
data_root="/home/mcn26/project_pi_skr2/shared/tabula_data"
primordial=scm.ortho.load(client,f"{data_root}/shendure",name)

Create a ground-truth dataframe from the description.

In [5]:
description=scm.describe_parameters(primordial.by_cell_type_parameters,
                        dat=primordial.training_data.data,
                        split="cell_type")
gt=description[["cell_type","cre_id","mu"]].groupby(["cell_type","cre_id"]).agg(true_mean=("mu","mean")).reset_index()
gt=scm.zero_pad_ground_truth(gt)
gt

            cell_type              cre_id  true_mean
0      Cardiomyocytes     Bend5_chr4_8174   0.063540
1      Cardiomyocytes     Bend5_chr4_8175   1.620998
2      Cardiomyocytes     Bend5_chr4_8179   0.053297
3      Cardiomyocytes     Btg1_chr10_9578   3.487160
4      Cardiomyocytes  Cdk5r1_chr11_12559   0.280126
...               ...                 ...        ...
1856  SurfaceEctoderm   Tubb2b_chr13_2578   0.000000
1863  SurfaceEctoderm   Txndc12_chr4_7969   0.000000
1864  SurfaceEctoderm   Txndc12_chr4_7971   0.000000
1866  SurfaceEctoderm   Txndc12_chr4_7975   0.000000
2071        reference   Txndc12_chr4_7969   0.000000

[2080 rows x 3 columns]

Abstract what the library looked like from the ortho training data. We will make the simplifying assumption that all MPRA bc are equal abundance in the original & none were lost.

In [6]:
library=primordial.training_data.data[["cre_id","mpra_bc"]].drop_duplicates()
abundance = 1/len(library)
library["abundance"]=abundance
library

                   cre_id          mpra_bc  abundance
0       Txndc12_chr4_7978  ACGTAACATTATAAT   0.000035
1          Klf4_chr4_3952  TGTTTAAGTCAACAA   0.000035
2        Foxa2_chr2_13840  CAACAACACATTTTA   0.000035
3               reference  TACCTAATGGGAAAG   0.000035
4        Lamc1_chr1_12152  AAATGGTAAAAGGCA   0.000035
...                   ...              ...        ...
751918  Epas1_chr17_10116  GGAACTCAGTCCGTT   0.000035
751919    Bend5_chr4_8174  AATTACAACTACCAA   0.000035
758757   Sparc_chr11_7233  GAGCGGGTTCAAGAT   0.000035
777357   Foxa2_chr2_13830  TACAATGCCCATTAT   0.000035
778285   Gata4_chr14_5729  GCGCTGGACTGTGGG   0.000035

[28300 rows x 3 columns]

Create object

In [7]:
simu_obj=scm.de_novo_simulation(
                        simulation_replicates=3,
                        experiment_bounds=scm.SHENDURE_BOUNDS,
                        ground_truth=gt,
                        library=library)

Simulate

In [8]:
simu_obj.gamut(client)

In [ ]:
DATA_ROOT="/home/mcn26/project_pi_skr2/shared/tabula_data/"

scMPRAforge: INFO: 2265/256680 cells (0.882%) have ≥1 multi-transfection event.
scMPRAforge: INFO: 2353/256632 cells (0.917%) have ≥1 multi-transfection event.
scMPRAforge: INFO: 2380/256663 cells (0.927%) have ≥1 multi-transfection event.

In [11]:
simu_obj.simulated_scMPRA

[<Future: finished, type: scMPRAforge.core.scMPRA_data, key: _wrap_helper-95948101903237eaedbca117cea37904>,
 <Future: finished, type: scMPRAforge.core.scMPRA_data, key: _wrap_helper-07f198ee578dd06af8dc0fdd01bba0ff>,
 <Future: finished, type: scMPRAforge.core.scMPRA_data, key: _wrap_helper-c34208fca89f49a514ed9388b83541ab>]

In [12]:
simu_obj.save(path=f"{DATA_ROOT}/simulated",name="shendure_calibrated_sim_20251111")

In [13]:
cluster.close()
client.close()