Notebook examines parameter recapitulation using synthetic data.

In [3]:
import sys
import os
import scMPRAforge as scm
import pandas as pd
import numpy as np
import scMPRAforge as scm

2025-07-28 13:34:41.858421: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-07-28 13:34:41.864600: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2025-07-28 13:34:41.864627: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

In [4]:
#autoreload for dev
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [5]:
#load ground truth
ground_truth_mu=pd.read_csv("../../notebooks/demos/parameter_extraction_demo/synthetic_ground_truth_carp.tsv",sep="\t")
ground_truth_mu=ground_truth_mu.set_index(['cell_type','cre_id'])
ground_truth_mu.head()

                      true_mu
cell_type cre_id
brain     reference         1
          mediumbody       10
          everybody       114
          redgene          30
          neurogene        99

In [6]:
#start a lightweighrt cluster
from dask.distributed import Client, LocalCluster
cluster=LocalCluster()
client = Client(cluster)

2025-07-28 13:35:52,511 - distributed.scheduler - WARNING - Removing worker 'tcp://127.0.0.1:33477' caused the cluster to lose already computed task(s), which will be recomputed elsewhere: {'_label_tensorzinb_regressors-0c85d47568056534fbcbedf8d7689e9c', '_smart_matrix-ed99a1d8f1860ac2c601139c5ae76fad', '_extract_zi-c9f1417c775878d8ef87f8a1fc45bff0', '_smart_matrix-b9f3238375b324ce40228bb9e8e8f66e', '_extract_theta-8c72e2f4ec3334f10e75d4269598c248', '_label_tensorzinb_regressors-20d8881b83323604e1aa8d8b3a874f58', '_extract_zi-27fcd1af429b94ec4a507de258c2db4e', '_extract_mu-ffb3e045ca6ed8f8c2eaa100812ec903', '_label_tensorzinb_regressors-0e75f7ae0faa05a9fcdb4b237ae61fe6', '_extract_mu-13567686f9835e1fe9c84fd340094abd', '_extract_zi-d92b6ee2427d9d00611bfbfe2490c2b8', '_extract_mu-f03268381f814f86b06af9c1b533b98d', '_extract_theta-7d8f81b08a7386c76a64ca5a15c53949', '_extract_mu-c2eaa96cfba9fb05878b44c099644d63', '_extract_mu-29be1977aa6c45951ff2bdaa2dcead03', '_extract_mu-bead037435095aa7914f76686a26f16a', '_extract_theta-985077bc295d7e17c5e947fa158ff8e4', '_extract_theta-4f752ad5248d007eb59209de838559a3', '_smart_matrix-c5a59ceb21bee91d75ebd5ca6308408d', '_extract_zi-4f6425feb579bed69456016c57a5e4bd', '_extract_zi-a5e41f8e311cac913c4b8fab6dd6aff5', '_extract_mu-52e95ac15c34c0ed5cf46f6703edaa7e', '_extract_theta-089c3a579873b5f0d851452c6c611569', '_smart_matrix-4a7b9b6cc32942ed32142dc98a72b76f', '_extract_mu-a79295e7ad7778f79e21968055ae4afd', '_extract_theta-4ecd414f7222837474d53d1ca9abd87d', '_extract_zi-d039ddae5fc55f9ee375a28abbe4e7d8', '_label_tensorzinb_regressors-930f26436775da9cc50fde199b3d7982', '_extract_zi-f27419ed534c4f07603a8564830bce2d', '_smart_matrix-a33a65a7cfbb2325926b6313fcbe2d7f', '_smart_matrix-923bd2adfcdb1e6f77d351ee5eaaf49f', '_extract_zi-f1de08526f0e3ade44c285361d3aa4b0', '_label_tensorzinb_regressors-22d0d8cbe2ba3adc06a08cb0763da081', '_extract_theta-182a16568c547883912056a3e65a0d9d', '_label_tensorzinb_regressors-f292054b0c0f11be3ffffee2552fd3b2', '_label_tensorzinb_regressors-a189994ef5dd6602fcf8cc59903540df', '_label_tensorzinb_regressors-8587cecba652be8009458e56d5574fb3', '_extract_theta-3534b44a3b3e5b74170d20d73508654e', '_extract_mu-f4086e2a93fafd5ceb5186be47c39ddb', '_extract_zi-8cfbff9cc1d3c7018b90eeb3606f0b6f', '_extract_mu-61afd6b17b3d460bbbeaf94f267fa4a8', '_smart_matrix-9586751ea69613295c8d425472f77882', '_extract_mu-4567678497887a3c04cb580d43bb419b', '_smart_matrix-9c9f11b7385c47ecd31587a7cd422453', '_smart_matrix-951822a20a6632987efe7e5811efd029', '_extract_theta-814c65bb7cad549e055b995a7bef5ae9', '_extract_theta-fbc806b76a1ad371b40e6c2e478bdb75', '_label_tensorzinb_regressors-ee2d41989dd58ecebec616a8dd2fb38e', '_extract_theta-b8ce3da16f2ab73c19a682769dbf6f78', '_label_tensorzinb_regressors-032180f62bc22760f4f2bc0fa491b5f0', '_smart_matrix-08973b679a0b3adb2d95e5efa4c08117', '_extract_zi-6ff0ca7f671b5c0447d58652698a515f', '_extract_zi-02ca40e84c04b60c3848700eb463140d', '_smart_matrix-8849eddef5173b087dd3f81d4259b960', '_label_tensorzinb_regressors-7178f0c8370f55067a4b8cbb1fe6c3cf'} (stimulus_id='handle-worker-cleanup-1753724152.5111995')

# Parameter extraction

In [7]:
dat=scm.scMPRA_data.from_tsv("/gpfs/gibbs/pi/reilly/tabula_data/simulated/fake_cres_v3.tsv")
dat.ortho_filter()
dat.set_negative_controls(["nobody","weak"])
dat.set_reference_cell("liver")

primordial=scm.ortho()
primordial.criss_cross(client=client,dat=dat)
primordial.extract_params(client)

scMPRAforge: INFO: Dropped 0 of 27 (cell_type, cre_id) combos with fewer than 3 nonzero entries.

In [8]:
scm.versus_truth(ground_truth_mu,primordial)

,by,mean_squared_error,mean_biased_error,mean_absolute_percent_error
0,cell_type,2.786826,-0.239707,11.786365
1,cre_id,2.633289,-0.268082,11.418997

In [9]:
cluster.close()